### ISSUE TITLE
Bootstrap 3 :: Date range selection :: Disabling dates in the past once start date is selected. 

### ISSUE THREAD

**Issue by samsonkhisty** [uxsolutions/bootstrap-datepicker#1031]
Similar to check in check out feature -> http://www.eyecon.ro/bootstrap-datepicker/ 

Once I select the start date, how do I disabled the end date calendar to disable the dates earlier than the start date. 

Any pointers appreciated.

**Comment by niranjans** [comment]
@acrobat I looked into the commit and the fix but I am not sure how this addresses this issue. In the [sandbox] (http://eternicode.github.io/bootstrap-datepicker/?markup=input&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#), if you navigate to `Range` option. How do you ensure that in the second input, you cannot select a date before what was selected in the first input? Right now, I am only able to disable dates in the past. 

For example - If I select the date "05/10/2015" in the first input, I can still select "05/08/2015" in the second input. Is it possible to disable this based on the first input selection?

Thanks
