### ISSUE TITLE
Locale not loading?

### ISSUE THREAD

**Issue by pdcmoreira** [uxsolutions/bootstrap-datepicker#1068]
Hello,

I've specified the following:

``` html
<div class="input-group date" id="renovar_picker">
    <input type="text" class="form-control" name="renovar_expira_em" required />
    <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
</div>
```

``` javascript
$('#renovar_picker').datepicker({
    format: "yyyy/mm/dd",
    language: 'pt',
    calendarWeeks: true,
    autoclose: true,
    todayHighlight: true
});
```

Folder structure:

```
css
| - datepicker
    | - datepicker3.css
js
| - datepicker
    | - bootstrap-datepicker.js
    | - locales
        | - bootstrap-datepicker.*.js
```

I've then imported the `css/datepicker/datepicker3.css`and the `js/datepicker/bootstrap-datepicker.js` files.
Everything seems to be working fine, except the languages - everything is english instead of the defined language.

**Comment by mdmamde** [comment]
I am not sure about the use of locales, 
1.)working fine if my custom.js includes the language:'XX' tag.
2.) i need the Datepicker localized, based on loading the locale XX.js file, ONLY
3.)i read about data-language. how to use please?

i ended up with 4 different custom.js with the language tag in it.
is 2.) possible?
