### ISSUE TITLE
Wrong width when set direction RTL

### ISSUE THREAD

**Issue by dev-mfm** [uxsolutions/bootstrap-datepicker#1079]
![244657f4-3524-11e4-9963-6d36ae0c90c7](https://cloud.githubusercontent.com/assets/8669854/4175258/8f62af1a-35c9-11e4-9521-fcab3fa27829.jpeg)

When adding this tool after setting the direction rtl, the width of the datepicker is increased
I use this tool https://github.com/morteza/bootstrap-rtl for setting the direction.

Does this tool support rtl?

**Comment by acrobat** [comment]
Fixed in #1192

**Comment by redayoub** [comment]
I'm having the same issue. when will this fixed please?

**Comment by Azaret** [comment]
Hi @redayoub this issue is fixed since `1.4.0`.
Can you try or confirm that you're using the latest version ?

**Comment by redayoub** [comment]
Hi @Azaret I'm using the version 1.6. I'm working on chrome Version 54.0.2840.59 (64-bit)
 ubuntu

**Comment by Azaret** [comment]
Can actually see it on sandbox.

**Comment by Azaret** [comment]
Don't mind me It's fixed on `1.7.0-dev`

**Comment by redayoub** [comment]
Thanks

**Comment by Amal50** [comment]
it is not working for me, it still has the same problem
