### ISSUE TITLE
What's wrong with the unix timeStamp?

### ISSUE THREAD

**Issue by highwater** [uxsolutions/bootstrap-datepicker#1115]
Everytime `changeDate` is fired, it returns the wrong `timeStamp` value, such as `1412988443255` which equals to `DATE (M/D/Y @ h:m:s): 10 / 27 / 45 @ 9:47:35pm UTC`. The returned `timeStamp` should be equal with `date` value that is also returned: `Thu Oct 02 2014 00:00:00 GMT+0700 (SE Asia Standard Time)`. Or we should not use time `timeStamp` value?

full object in 'changeDate' event

```
currentTarget: input#app-date.form-control
data: undefined
date: Thu Oct 02 2014 00:00:00 GMT+0700 (SE Asia Standard Time)
    __proto__: Invalid Date
dates: Array[1]
    0: Thu Oct 02 2014 00:00:00 GMT+0700 (SE Asia Standard Time)
    length: 1
    __proto__: Array[0]
delegateTarget: input#app-date.form-control
format: function (){return a.apply(b||this,e.concat(d.call(arguments)))}
handleObj: Object
isTrigger: 3
jQuery21107133297212421894: truenamespace: ""
namespace_re: null
result: undefined
target: input#app-date.form-control
timeStamp: 1412988443255
type: "changeDate"
__proto__: Object
```

Edit: okay okay.. i figured out that the `timeStamp` value is intended to be equal with `now` time and I was supposed to extract `timestamp` via the `date` property.

**Comment by highwater** [comment]
@timmy78 I forgot but I think I ended up **not** using that value as the timestamp that I wanted.

**Comment by itfunpeople** [comment]
@timmy78 

Display the date in expanded Locale format.

`var date = new Date(appDate.timeStamp);`

Same below,

`appDate.date`

Format a date into a string value with a specified format.
Display the date in ISO format. Produces "2015-04-03".

`$.datepicker.formatDate('yyyy-mm-dd', new Date(appDate.date));`
