### ISSUE TITLE
Datepicker z-index problem inside modal

### ISSUE THREAD

**Issue by betonetotbo** [uxsolutions/bootstrap-datepicker#1129]
When you put the boostrap datepicker inside a boostrap modal, the popup shows behind the modal.

This occurs because the code assumes the first element as the bigger zIndex inside the **place** function:

```
  var zIndex = parseInt(this.element.parents().filter(function(){
        return $(this).css('z-index') !== 'auto';
  }).first().css('z-index'))+10;
```

The FIX:

Iterate over all parents to discover the biggest zIndex:

Here is my code:

```
        var biggestZIndex = 0;
        this.element.parents().each(function(index, parent) {
            var zIndex = $(parent).css('z-index');
            if (zIndex !== 'auto') {
                var zIndex = parseInt(zIndex);
                if (zIndex > biggestZIndex) {
                    biggestZIndex = zIndex;
                }
            }
        });
        var zIndex = biggestZIndex + 10;
```

**Comment by bainguyendeveloper** [comment]
I use this in css
.modal-open .ui-datepicker{z-index: 2000!important}

**Comment by eviltek2099** [comment]
I fixed with ```ul.uib-datepicker-popup.dropdown-menu.ng-scope {
    z-index: 1090 !important;
}```
