### ISSUE TITLE
do you need to translate it into Chinese

### ISSUE THREAD

**Issue by jasonwwl** [uxsolutions/bootstrap-datepicker#1132]
i like your project, do you need to translate it into Chinese?  i can help you with that.

**Comment by PhilPJL** [comment]
Windows / IE considers simplified Chinese to be zh-Hans or zh-CN.
Plus there are several other variants.  It would be useful to add further support.

![snip](https://cloud.githubusercontent.com/assets/271656/14492493/7c8030cc-0177-11e6-83ac-0fef2d661e87.PNG)
