### ISSUE TITLE
extra class selectors in dist/css/bootstrap-datepicker3.css

### ISSUE THREAD

**Issue by ddcahutton** [uxsolutions/bootstrap-datepicker#1311]
This is an issue with v1.4.0 (it looks like older releases did not include a dist/ directory).

See https://github.com/eternicode/bootstrap-datepicker/blob/v1.4.0/dist/css/bootstrap-datepicker3.css#L480

`.active.active` seems like unintentional specificity. This issue appears elsewhere in the /dist/css if more examples are needed.

**Comment by acrobat** [comment]
Older releases had their compiled css in the `css` dir, but it was also an issue [in 1.3.1 ](https://github.com/eternicode/bootstrap-datepicker/blob/1.3.1/css/datepicker3.css#L486). I will take a look at the less files what causes this issue!

**Comment by vsn4ik** [comment]
Fixed in #1638.
