### ISSUE TITLE
Date Deselect Issue

### ISSUE THREAD

**Issue by ethikz** [uxsolutions/bootstrap-datepicker#1341]
I've went through the issues and noticed this was supposed to be fixed but I'm still seeing the issue.

I have all days disabled by default.  I'm loading in ajax that will remove disabled from a day that corresponds to data I'm receiving back from the API.  I can select those dates and deselect them still.  Is there a way to disable that functionality?

This is not multidate, it's a single day

**Comment by acrobat** [comment]
Can you provide a jsfiddle example for this issue? (you can use [this jsfiddle](http://jsfiddle.net/vh1oknf7/) as a base)

**Comment by vdzundza** [comment]
I have the same issue.

**Comment by hebbet** [comment]
@vdzundza Can you provide a jsfiddle example for this issue? (you can use [this jsfiddle](http://jsfiddle.net/vh1oknf7/) as a base)

**Comment by ethikz** [comment]
I forgot and currently do not work where I was working where I had that issue.  If I run across again I'll post a fiddle or if someone else does they can as well.
