### ISSUE TITLE
year, year-month, year-month-day picker possibilities

### ISSUE THREAD

**Issue by nareshv** [uxsolutions/bootstrap-datepicker#145]
Given the way  current datepicker is implemented. Its possible to have year picker, year-month picker along with the current date picker alone.

I've tried to do it automatically with parseDate, but didn't had success. So, this alternative version.

diff against current version is https://gist.github.com/3169847

Here is the code which shows the picker in action

&lt;!doctype html&gt;
&lt;html&gt;
    &lt;head&gt;
        &lt;meta charset='utf-8'&gt;
        &lt;script type=&quot;text/javascript&quot; src=&quot;jquery-1.7.2.min.js&quot;&gt;&lt;/script&gt;
        &lt;script type=&quot;text/javascript&quot; src=&quot;bootstrap-datepicker.js&quot;&gt;&lt;/script&gt;
        &lt;link rel=&quot;stylesheet&quot; href=&quot;bootstrap.2.0.4.css&quot;&gt;
        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;datepicker.css&quot;&gt;
    &lt;/head&gt;
    &lt;body&gt;
        &lt;div class=&quot;container&quot;&gt;
            &lt;form class=&quot;form form-horizontal&quot;&gt;
                &lt;input type=&quot;text&quot; id=&quot;a&quot; date-date-format=&quot;dd/mm/yyyy&quot;/&gt;
                &lt;input type=&quot;text&quot; id=&quot;b&quot; date-date-format=&quot;mm/yyyy&quot;/&gt;
                &lt;input type=&quot;text&quot; id=&quot;c&quot; date-date-format=&quot;yyyy&quot;/&gt;
            &lt;/form&gt;
        &lt;/div&gt;
        &lt;script type=&quot;text/javascript&quot;&gt;
            $('#a').datepicker({startView : 'month', format : 'dd/mm/yyyy', enableYearToMonth: true, enableMonthToDay : true});
            $('#b').datepicker({startView : 'year', format : 'mm/yyyy', enableYearToMonth: true, enableMonthToDay : false});
            $('#c').datepicker({startView : 'decade', format : 'yyyy', enableYearToMonth : false, enableMonthToDay : false,});
        &lt;/script&gt;
    &lt;/body&gt;
&lt;/html&gt;

**Comment by gchjob** [comment]
@sidronsile 添加一个配置项即可: {minViewMode: 1}，this my solution:
$('.date-picker').datepicker({
            format: "yyyy-mm",
            minViewMode: 'months', // or 1, 月选择
            startView: 'decade' // or 2, 10年选择
        }).on('changeMonth', function(e) {
            $(e.currentTarget).data('datepicker').hide();
        });

**Comment by jitendraF5buddy** [comment]
its not working

**Comment by splashes** [comment]
Hi,
I was using minViewMode to select months as a range. For e.g., January - March. But as it is stated in docs as 

> The day is set to the 1st for “months”, and the month is set to January for “years”, the year is set to the first year from the decade for “decades”, and the year is set to the first from the millennium for “centuries”  [HERE](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#minviewmode)

If we are using minViewMode for range, then i need to select from January - 1st to March - 31st. And not March 1st as it would select now.

Is there any option to change the selected date when using minViewMode?
