### ISSUE TITLE
forceParse is wrongly correcting my correct input

### ISSUE THREAD

**Issue by Hejado** [uxsolutions/bootstrap-datepicker#1472]
First, I thought, it might be an error on my side, so I posted a question at SO: http://stackoverflow.com/questions/30617209/unintended-reset-of-bootstrap-datepicker-when-using-angularjs/31182765#31182765

Setting a date value with angularjs via ngModel, clicking in the input field and deselecting, without checking a date in the datepicker: the date value will be resetted to the initial value. See: http://jsfiddle.net/hejado/xqqmpct9/14/

This issue can be fixed by setting forceParse to false (http://jsfiddle.net/hejado/xqqmpct9/16/) but that's not more than a quick workaround for what I believe to be a bug. In the fiddles, you can see, that valid date strings are dismissed and deleted by the datepicker.

**Comment by kylebcooke** [comment]
I am having the same problem, when the value field of the input is set correctly with a knockout.js data-bind the calendar does not parse the data correctly and clicking off the calendar clears the date. To avoid this I have disabled forceParse for a workaround until this is resolved.
