### ISSUE TITLE
Multiple linked datepickers?

### ISSUE THREAD

**Issue by entozoon** [uxsolutions/bootstrap-datepicker#1477]
As unusual as you might think, I often have to make a set of datepickers that are essentially the same field.

For example here, all three datepickers are essentially the same datepicker, but different months within it:
![multi datepickers](http://i.imgur.com/X5NFpIJ.png)

Similar to the ui-datepicker-multi-3 functionality of jqueryui datepicker.
Also of course they'd need to be always visible.

Is this relatively easily achievable, I'd rather stick with this datepicker if possible..

**Comment by jelhan** [comment]
Duplicate of #1154
