### ISSUE TITLE
update datepicker (update method) with a date that is less than the date initialized to the startDate

### ISSUE THREAD

**Issue by sebasladino** [uxsolutions/bootstrap-datepicker#1487]
Hi, I need to upgrade a datepicker with a date that is earlier than the initialized in the startDate.
example code:

``` javascript

//init datepicker
$("#input").datepicker({
          'format': "yyyy-mm-dd",
          'startDate': new Date(), //2015-07-14
          'autoclose': true
});

//update datepicker
$("#input").datepicker('update', "2015-07-13");
```

At the time of this input is empty, any idea of how to do it,
thanks.

**Comment by typeoneerror** [comment]
Don't use the startDate option. Any dates before that date will be Invalid.

**Comment by fernandoGN** [comment]
I have a same problem, when i use update on datepicker i lost all configurations.
```javascript
//init
$(element).datepicker({
				     todayHighlight: true,
				     autoclose: true,
				     format: "dd/mm/yyyy",
				      language:"pt-BR"
				});

//update, in this moment i lost language configuration.
$(element).datepickert('update','');
```
Trying resolve this problem...

**Comment by fernandoGN** [comment]
For me this solved the problem:
```javascript
$element.data('datepicker').setDate('');
```
With this i can change/update value and don't lost my configurations.
