### ISSUE TITLE
Configure language via markup

### ISSUE THREAD

**Issue by m-borja** [uxsolutions/bootstrap-datepicker#1540]
Languge can't be provided via data-attributes, `data-language` is not working.
I try with **fr** localization.

**Comment by hebbet** [comment]
data works for most features, not for all, as noted in the documentation.

http://bootstrap-datepicker.readthedocs.org/en/latest/options.html

**Comment by m-borja** [comment]
Thanks for the answer.

Is there any detailled list of which option are available for markup configuration ?

**Comment by HuBandiT** [comment]
@m-borja - `data-date-language` allows you to change the language already. do you specifically need `data-language` for some reason?

**Comment by m-borja** [comment]
ok, i haven't notice that i can use this option...

**Comment by HuBandiT** [comment]
ok, so please try it, and if it works, please come back and comment here that the issue can be closed.
