### ISSUE TITLE
Option defaultViewDate as data attribute

### ISSUE THREAD

**Issue by astrapi69** [uxsolutions/bootstrap-datepicker#1611]
Hi folks,

can somebody tell me how to set the defaultViewDate as an data attribute?

I tried the following but did not work:

```
       data-date-default-view-date-year="1977" 
       data-date-default-view-date-month="0" 
       data-date-default-view-date-day="1"
```

**Comment by lindem** [comment]
from the code it looks like the defaultViewDate cannot be set as a data attribute. The region in question is (line 297 onwards, in a debugger):
```js
			if (o.defaultViewDate) {
				var year = o.defaultViewDate.year || new Date().getFullYear();
				var month = o.defaultViewDate.month || 0;
				var day = o.defaultViewDate.day || 1;
				o.defaultViewDate = UTCDate(year, month, day);
			} else {
				o.defaultViewDate = UTCToday();
			} 
```

if you put an object literal (like, JSON, which is already questionable to put into attributes) into the attribute, this region sees a string. A string has no `year`, `month` or `day` fields, hence it gets the defaults. If you put the subfields like you did into the element, the other path will be used (defaultViewDate will be empty then).

So there currently seems no way to do it; and if I am wrong, somebody shouldn't wait to correct me.
