### ISSUE TITLE
Two test failed on timezone 'America/New_York'

### ISSUE THREAD

**Issue by vsn4ik** [uxsolutions/bootstrap-datepicker#1655]
For reproduce add to `Gruntfile.js` export function:
~~`process.env.TZ = 'Europe/Moscow';`~~
`process.env.TZ = 'America/New_York';`
and run `grunt test`

**Comment by acrobat** [comment]
@vsn4ik is this still relevant after PR #1654? Or is it specific with timezone `Europe/Moscow`?

**Comment by vsn4ik** [comment]
Still relevant. Reproduce on `America/New_York`.

**Comment by acrobat** [comment]
@vsn4ik shouldn't we keep this issue open if it's still reproducible?
