### ISSUE TITLE
Single click in IE7/8 doesn't work

### ISSUE THREAD

**Issue by railyboy** [uxsolutions/bootstrap-datepicker#174]
I've done some testing on a project that I'm working on to build my skills and when I came to test with my friends end client browser (that he has to support) IE7 minimum (on XP so IE8 is max they would use), I found that the datepicker doesn't respond to single clicks, only double clicks.

Googling there appears to be a patch for this at https://github.com/Aymkdn/Datepicker-for-Bootstrap.

Still being new at this I'm not sure about practicalities of taking your code, modifying it by integrating the change in the code base above. I come from a proprietary software background so am used to giving credit to the organisation I work for. Here I think I could set-up my own version and point back to yours but not sure of the best way to go about this.

I have the following jsFiddle which demonstrates this.

http://jsfiddle.net/railyboy/eFKeF/5/

The difference in this code and what is currently in that of Nerians and yours is that I have added the following click event.

`if (this.isInput) { ..
      click: keydown: $.proxy(this.keydown, this),
      click: $.proxy(this.click, this)`

And to the this.element.find('input').on({ section

I have taken the code from Nerian's rails bootstrap datepicker which I am using in my Rails app. My limited understanding is that this has most/all of your fixes in.

I forked your repo, and attempted to fix this, but my current jQuery knowledge is limited and I have not been successful. I thought I'd try my attempts in jsFiddle to prove it wasn't something with my environment (Mac OSX - Lion, ruby 1.9.3, rvm, running Windows XP VM with IE7/Windows Vista VM with IE8 via Virtual Box)

**Comment by pictoru** [comment]
Hi there. I have a similar issue. I use Bootstrap 3 and jQueryUI Dialog not Bootstrap's Modal. When selecting date I have to double click the day to select it and apply it to input field. This issue happens only when I'm in a dialog popup. I use IE11 for testing. In other browsers everything is fine, it works as is should. Do you have any suggestion?
