### ISSUE TITLE
bootstrap-datepicker on jsdelivr

### ISSUE THREAD

**Issue by krzyko** [uxsolutions/bootstrap-datepicker#1791]
Good day,
are there any chances to see bootstrap-datepicker hosted also on www.jsdelivr.com cdn? I'd like to use same cdn network across single project and bootstrap-datepicker missing. Adding a project seems easy and maintaining it is automatic.
Best wishes,
Krzysztof Kosz

**Comment by acrobat** [comment]
I don't know if it's necessary to add the libary to another cdn. The library is currently available on [cdnjs](https://cdnjs.com/libraries/bootstrap-datepicker). So maybe this is fix/answer for you question?

**Comment by krzyko** [comment]
Loading all the libraries from single CDN should reduce loading time (saving DNS lookups). I've considered switching to cndjs, but unfortunately due to their internal regulations (issue described here: https://github.com/cdnjs/cdnjs/issues/2984) they don't host "respond-proxy.html" file, which is necessary for respond.js to function properly when used with cdn network. So only solution for now is to use two cdn networks (jsdelivr for respond.js and cdnjs for bootstrap-datepicker) within single project which is something I'd like to avoid.

**Comment by acrobat** [comment]
Ok, I see the usecase! I will look into to this in the next few days/weekend! Will give you an update about this here!

**Comment by krzyko** [comment]
It's good to hear this. Thank you for taking care.

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

**Comment by krzyko** [comment]
Brilliant! Thanks for the information - it's all working good.
