### ISSUE TITLE
Incorrect z-index check

### ISSUE THREAD

**Issue by tleunen** [uxsolutions/bootstrap-datepicker#1793]
[At these lines](https://github.com/eternicode/bootstrap-datepicker/blob/master/js/bootstrap-datepicker.js#L709-L710), the second condition doesn't make sense and will always be false.
Here's the specific code:

```
var itemZIndex = $(this).css('z-index');
if (itemZIndex !== 'auto' && itemZIndex !== 0) parentsZindex.push(parseInt(itemZIndex));
```

`itemZIndex` will always be a string, so you cannot use the strict equals in this case. Or if you want, you have to compare with a string. But what I suggest is parsing the value at the source instead of doing it when adding it in the array, and you should use `parseInt(itemZIndex, 10)`.

**Comment by acrobat** [comment]
@tleunen Can you provide a PR for this check? We can discuss the fix in the PR!
