### ISSUE TITLE
Set startDate based on another datepicker date selection (without date-range picker)

### ISSUE THREAD

**Issue by isfak** [uxsolutions/bootstrap-datepicker#1801]
Hello all,

I am creating some kind of reservation system for a hotel. I have 2 separate datepickers, one for selecting the arrival date and one for selecting the departure date of the guest.
When the user sets the arrival date via the first datepicker, I would like to set the startDate property of the departure date datepicker to the arrival date, so that the guest cannot select departure date prior to arrival date. I don't want to use date-range picker for this.

Thanks in advance!

**Comment by daryllabar** [comment]
I have the same issue.  I was able to get around it by calling this function in my TypeScript:

    function resetDatePicker(picker: JQuery, minDate: Date, value?: Date): JQuery {
        const date = value || picker.datepicker("getDate");
        picker.removeData("datepicker");
        picker.datepicker({
            startDate: minDate
        } as DatepickerOptions);
        picker.datepicker("update", date)
              .on("changeDate", onChange);
        return picker;
    }

**Comment by JZwanepoel1996XD** [comment]
+1

**Comment by Azaret** [comment]
Hi, sorry for the "late" reply.
For the record, here's a snippet: https://jsfiddle.net/azaret/25bqa6ho/
