### ISSUE TITLE
Datepicker incorrectly reverts input value after form reset.

### ISSUE THREAD

**Issue by ravshansbox** [uxsolutions/bootstrap-datepicker#1834]

**Comment by hebbet** [comment]
can you please provide an example of your problem?

**Comment by ravshansbox** [comment]
Here is an example:
https://jsfiddle.net/ravshansbox/asy3sgLc/

datepicker by default has a value.
change the value, then press "Reset" button, the focus the datepicker and without selecting any date leave it(click somewhere else), value gets reverted back to last selected before form reset.
