### ISSUE TITLE
Serbian locales -> "sr" code does not belong to Serbia

### ISSUE THREAD

**Issue by usarskyy** [uxsolutions/bootstrap-datepicker#1856]
Hello,

repository contains the following Serbian locale files:
- bootstrap-datepicker.rs.js
- bootstrap-datepicker.rs-latin.js
- bootstrap-datepicker.sr.js
- bootstrap-datepicker.sr-latin.js

Accordingly to [Wikipedia](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) "SR" code does not belong to Serbia, it is [Suriname](https://en.wikipedia.org/wiki/Suriname)

Fix of this issue is quite simple: either to update bootstrap-datepicker.sr.\* files with correct translation, or drop them at all.

**Comment by acrobat** [comment]
The list you are looking at is the ISO list of country codes (ISO 3166) we use [ISO 639](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) (the language code iso standard) to identify the language codes. But "rs" should be deprecated (and removed in 2.0) as it's an incorrect language code!

**Comment by acrobat** [comment]
I've added the deprecation notice in 0ae9678. Translations will be removed in 2.0

**Comment by vsn4ik** [comment]
Thanks @usarskyy!
