### ISSUE TITLE
.datepicker-orient-top arrow bad positioning

### ISSUE THREAD

**Issue by peterekjs** [uxsolutions/bootstrap-datepicker#1880]
even with property `bottom` set to pseudo-elements on .datepicker-dropdown.datepicker-orient-top, there are still active `top` properties previously set on .datepicker. (probably it will make similar issues with left-right classes)

Suggest to put some resets into positioning classes e.g.:

```
.datepicker-dropdown.datepicker-orient-top {
    &::before,
    &::after {
        top: initial;
    }
}
```

**Comment by Azaret** [comment]
I'm not sure to understand what you're trying to achieve.
Could you elaborate more ?

**Comment by stebru** [comment]
I've also run into an issue with bad positioning of the arrow. Setting orientation explicitly doesn't help either. 

As you can see, the picker itself is positioned correctly, but the arrow points in the wrong direction:
![eb29278636abd3424e18b3adf6ef433d](https://cloud.githubusercontent.com/assets/24052/15142971/b0fa2b38-16a7-11e6-8399-6cfbcce0f087.png)
![e56b2871008172a649a9c3de8b93699a](https://cloud.githubusercontent.com/assets/24052/15143133/76580b70-16a8-11e6-9d2f-923a6b79424f.png)

**Comment by StepanMas** [comment]
+1
![61b571214d](https://cloud.githubusercontent.com/assets/6086962/15738416/38437f6a-28bc-11e6-80d0-3dc52faf9e2c.png)

**Comment by biggu0** [comment]
＋1

**Comment by anpegar** [comment]
https://github.com/eternicode/bootstrap-datepicker/issues/1816

**Comment by taiansu** [comment]
+1 on 1.6.4

**Comment by julianfox** [comment]
+1

**Comment by machinefriendly** [comment]
I have the same issue, I don't have a solution to correct that arrow direction, I just remove it by removing below-shown codes from the .css file, waiting for a final solution from others:
.datepicker-dropdown:before {
content: '';
display: inline-block;
border-left: 7px solid transparent;
border-right: 7px solid transparent;
border-bottom: 7px solid #999;
border-top: 0;
border-bottom-color: rgba(0, 0, 0, 0.2);
position: absolute;
}
.datepicker-dropdown:after {
content: '';
display: inline-block;
border-left: 6px solid transparent;
border-right: 6px solid transparent;
border-bottom: 6px solid #fff;
border-top: 0;
position: absolute;
}
.datepicker-dropdown.datepicker-orient-left:before {
left: 6px;
}
.datepicker-dropdown.datepicker-orient-left:after {
left: 7px;
}
.datepicker-dropdown.datepicker-orient-right:before {
right: 6px;
}
.datepicker-dropdown.datepicker-orient-right:after {
right: 7px;
}
.datepicker-dropdown.datepicker-orient-bottom:before {
top: -7px;
}
.datepicker-dropdown.datepicker-orient-bottom:after {
top: -6px;
}
.datepicker-dropdown.datepicker-orient-top:before {
bottom: -7px;
border-bottom: 0;
border-top: 7px solid #999;
}
.datepicker-dropdown.datepicker-orient-top:after {
bottom: -6px;
border-bottom: 0;
border-top: 6px solid #fff;
}

**Comment by jadrake75** [comment]
+1 I am also seeing this issue.

I would appear (perhaps I am wrong) that using an orientation of "auto left" will default to top first and bottom secondarily.  I would think this would be the other way by default.

**Comment by joelklingler** [comment]
I fixed it using the following JS:

https://github.com/soulim/ember-cli-bootstrap-datepicker/issues/78#issuecomment-296571933

**Comment by hughanderson4** [comment]
I noticed this behavior when I updated my installation of Bootstrap Datepicker.  I updated the .js file but forgot to also update the .css file.  I had wrong arrow.  Once I updated also the css file to latest version, my arrows work correctly now.
