### ISSUE TITLE
Add versioning and repo tagging

### ISSUE THREAD

**Issue by leesmith** [uxsolutions/bootstrap-datepicker#192]
Organization never hurts.  First, pick a version number since there doesn't seem to be one.

It would be nice to have version numbers in the headers of the js and css files.  Version tags in the repo are also nice.  Many thanks!

http://semver.org/

**Comment by brandonros** [comment]
As an average user, I really can't figure out what I need to download.

https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css

https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker3.css

I am going to assume the difference between those two files is that one is for Bootstrap 2, and one is for Bootstrap 3.

So, I would expect:

https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js

and 

https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker3.min.js

but the latter does not exist...

**Comment by acrobat** [comment]
javascript had nothing to do with twitter bootstrap so there is only 1 javascript file named `bootstrap-datepicker(.min).js`. The css files have specific classes which apply to each version of twitter bootstrap. 

For more info about the [different stylesheet files](https://bootstrap-datepicker.readthedocs.io/en/latest/#stylesheets), you can read the section we've added to docs.
