### ISSUE TITLE
cannot call method 'split' of undefined - ajax modal

### ISSUE THREAD

**Issue by mylesthedev** [uxsolutions/bootstrap-datepicker#193]
Had an issue when i was calling a modal and loading a page via ajax..

The page had a datepicker which values was set via php

It worked the first time but if you closed the modal and re-opened it, it would lose the value of date which caused the date.split(format.separator) to fail which failed all other plugins.

Not sure why this was happening.

Had to revert to normal jquery datepicker as no time to mess around with it.

**Comment by Ajitweb** [comment]
Thank you @songaal 
Now after your hack and also playing around with z-index, the datepicker works great with bootstrap modals  :+1:

**Comment by cyberformed** [comment]
Thank you! Replacing the file with eyecon and it works!
