### ISSUE TITLE
startDate not working correctly ?

### ISSUE THREAD

**Issue by FLasH3r** [uxsolutions/bootstrap-datepicker#195]
Iv'e set up a small fiddle to show the bug.

set the startDate to 20.08.2012, but the limit starts from 20.09.2012

Am i doing something wrong?

http://jsfiddle.net/sourcecode_il/yEGZB/

**Comment by fatuhoku** [comment]
Doesn't work for me. startDate doesn't do anything when passing it in through the initialization dictionary.

**Comment by bensonism** [comment]
Still not working

**Comment by acrobat** [comment]
If it is not working please create a new issue referencing this issue and provide a jsfiddle with the latest release so we have a testcase. Thanks!

**Comment by bensonism** [comment]
Sorry, looks like the site was using an out of date version of bootstrap.datepicker.js, it is working great!

**Comment by acrobat** [comment]
No problem! Thanks for the feedback!
