### ISSUE TITLE
Multiple disabled dates comma separated doesn't work with 1.6.1

### ISSUE THREAD

**Issue by slaviktim** [uxsolutions/bootstrap-datepicker#1960]
Doesn't allow to set disabled dates like 08/01/2016,08/02/2016 - only single date allowed. I've modified local copy with the next code:

o.datesDisabled = o.datesDisabled||[]; // present code
// added code in _process_options function 
var str = o.datesDisabled;
var patt = /\d,/g;
if(patt.test(str)) {
      o.datesDisabled = str.split(",");
}
// end  

ex. 1.6.1.

**Comment by jelhan** [comment]
Following docs you should provide an Array of date strings or a single date string. Comma separated dates are not supported. https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#datesdisabled
