### ISSUE TITLE
setDate and / or Update 

### ISSUE THREAD

**Issue by mustafaarun** [uxsolutions/bootstrap-datepicker#1976]
### Expected behaviour
should only update date, keeping initialized options for example "format" or "startDate"

### Actual behaviour
options resets

### Datepicker version used
v1.6.0

**Comment by jelhan** [comment]
Could you please provide a JSFiddle reproducing the issue? I tried but wasn't able: https://jsfiddle.net/3mzwhz0u/

**Comment by mustafaarun** [comment]
hello,

i think my error is init datepicker via parent div : https://jsfiddle.net/3mzwhz0u/1/

**Comment by nicozimmermann94** [comment]
Can confirm this:
if setup via div (class .date on parent div, because using input+button), then setDate will ignore the specified format

**Comment by mustafaarun** [comment]
i tried to reproduce the issue but i failed, i think my setup had another error.
so answer to your question is no.

can check it out : https://jsfiddle.net/3mzwhz0u/3/

**Comment by ppbustamante** [comment]
options resets too

**Comment by Azaret** [comment]
Actually no. This is not a bug, my bad.

I think you're creating the datepicker on the `div`, then you're updating the datepicker on the `input`, so it is creating a new datepicker. You must initiate and call methods on the same DOM element.

```javascript
$('#div').datepicker({
  format: 'dd/mm/yyyy'
});
$('button').on('click', function() {
  $('#div').datepicker('setDate', new Date(2015, 7, 31));
});
```
