### ISSUE TITLE
Missing namespace for 'show' event causes problems for other event listeners.

### ISSUE THREAD

**Issue by andrews05** [uxsolutions/bootstrap-datepicker#1979]
Whenever the datepicker gets shown it triggers a 'show' event with no namespace, which causes it to get picked up anything listening for 'show.*' as it bubbles up.

I have a datepicker inside a bootstrap collapse element with a listener on the collapsible for 'show.bs.collapse'. When the datepicker gets shown my listener thinks the collapsible was shown and causes odd behaviour.

This can easily be fixed by including a namespace when triggering the 'show' event.

**Comment by renalpha** [comment]
https://github.com/eternicode/bootstrap-datepicker/pull/642
