### ISSUE TITLE
German language setting

### ISSUE THREAD

**Issue by faxe1008** [uxsolutions/bootstrap-datepicker#1996]
Greetings,

I wanted to set the language of the datepicker to german. The code:
$('.datepicker').datepicker({
langauge:"de",
format: "dd.mm.yyyy",
autoclose: true,
todayHighlight: true,
todayBtn:true
});

Maybe it is interesting to know that I'm using it in a XPage site.
### Actual behaviour

It remains english.

### Datepicker version used

1.6.1

**Comment by brstra** [comment]
Have you added locale file after datepicker.js? Something like this:
`<script src="/js/locales/bootstrap-datepicker.de.js"></script>`

**Comment by fbitterlich** [comment]
@faxe1008 , I noticed in your post you have a typo in `language` (you wrote "langauge"). Do you have that error in your code too? That might be the source of the problem.

**Comment by huchim** [comment]
I've the same problem in version 1.6.1.

```
<script src="/Scripts/locales/bootstrap-datepicker.es.min.js"></script>
<script type="text/javascript">
        $(function () {
            $(".datepicker").datepicker({
                format: 'dd/mm/yyyy',
                language: 'es',
                autoclose: true
            });
</script>
```

**Comment by Azaret** [comment]
Hi,

Looks like working in 1.6.1 and 1.7.0-dev, and I guess both of you had a typo.
Closing unless some feedback from OP.
