### ISSUE TITLE
Month selector returning 1 month later than the 1 selected

### ISSUE THREAD

**Issue by YeshaS93** [uxsolutions/bootstrap-datepicker#1999]
**Expected behaviour**
The month selector should return the month chosen.

**Actual behaviour**
If the system date is 31st August and I choose September month, the date object in the event comes out to be 1st October. 

**Datepicker version used**
3.3.4

**Example**

_click function for the picker:_ 
```
case 'span':
if ( target.is( '.month' ) ) {
                            var month = target.parent().find( 'span' ).index( target );
                            this.viewDate.setMonth( month );
}
```

If` viewDate = 31st August, target = 8: this.viewDate.setMonth( month ) => returns 1st October`. This behaviour is justified in the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/setMonth 
):
As 31st September is not a valid date, it will be converted to 1st October.

**Comment by YeshaS93** [comment]
We should probably set viewDate to the 1st of the viewDate's month.
```this.viewDate = new Date(viewDate.getFullYear(), viewDate.getMonth(), 1);
this.viewDate.setMonth(target);```

**Comment by Azaret** [comment]
Hi,

Current versions are `1.6.4` for stable and `1.7.0` for dev.
I think you're on the wrong repositories.
