### ISSUE TITLE
Add datepicker-switch for chenge year to datepicker-days window,

### ISSUE THREAD

**Issue by pavelgronsky** [uxsolutions/bootstrap-datepicker#2013]
### Expected behaviour

Hello. I need to add datepicker-switch for change year to the  datepicker-days window. I need to show day block, datepicker-switch mounc and datepicker-switch year on one firs window bootstrap-datepicker
. How can I do that? 
### Actual behaviour

Tell us what happens instead.
### Datepicker version used

ex. 1.6.0.
### Example code

Jsfiddle example to reproduce the problem.

**Comment by Azaret** [comment]
Hi,

I'm sorry but I'm not sure to understand what you want.
If English is not your thing, try with simple sentences, and a bit of help from a Google Translate.
