### ISSUE TITLE
In a linked calendar, how do I set the beginning date of the second calendar?

### ISSUE THREAD

**Issue by meatballcoder** [uxsolutions/bootstrap-datepicker#2019]
### Expected behaviour
What I want is that when I pick the first calendar, the second calendar is limited to the start date of three days past the first calendar.  So if I picked 09/23/2016, three days are automatically added to the second one 09/26/2016.  For example, if I have a hotel booking and it requires a minimum of three days, I want to restrict it to only three days plus.  I have tried to find the answer in the documentation.

### Actual behaviour
Adds one day.

### Datepicker version used

ex. 1.6.1.

### Example code

I have tried this,

$("#datepicker-booking-container #frmBookingStartDate").on("change",function (e) {
   $("#datepicker-booking-container  #frmBookingEndDate").datepicker({startDate:3});
}); //and tried many other things.

**Comment by Azaret** [comment]
Hi,

Not sure if this snippet works in the latest.
Hopefully this kind of behavior will be easier to implement in the next versions.

```javascript
(function(){
    var from, to, from_date, to_date;

    from = $('#frominput');
    to = $('#toinput');

    from.datepicker({
        beforeShowDay: function() {
            if (to_date !== undefined) {
                if (date > to_date) {
                    return false;
                }
            }
            return true;
        }
    });
    from.on('changeDate', function (event){
        from_date = event.date;
        to.data('datepicker').update();
        from.data('datepicker').update();
    });

    to.datepicker({
        beforeShowDay: function() {
            if (from_date !== undefined) {
                if (date < from_date) {
                    return false;
                }
            }
            return true;
        }
    });
    to.on('changeDate', function (event){
        to_date = event.date;
        from.data('datepicker').update();
        to.data('datepicker').update();
    });
});
```
