### ISSUE TITLE
Append div to specific dates

### ISSUE THREAD

**Issue by reachtokish** [uxsolutions/bootstrap-datepicker#2037]
Hi, Can I append div to some specific dates? if yes then how?

Thanks

**Comment by Azaret** [comment]
Hi,

May I ask you your end goal ?
The easy way to 'catch' a date would be to add a specific CSS class with [`beforeShowDay`](https://bootstrap-datepicker.readthedocs.io/en/stable/options.html#beforeshowday).
Unfortunately there is no way push html code in `beforeShowDay`, nor an event triggered when dates change.
We might be able to help you with more information.

**Comment by reachtokish** [comment]
Thanks for reply

I was trying to do a event calendar by bootstrap datepicker and I need a tooltip into some of the specific dates but Now I have choose another library for that.

Thanks :)

**Comment by Azaret** [comment]
Yeah there is no build-in functionality for that.

A way I can think of would be to use `beforeShowDay` in order to tag the date you need to.
Then you could catch `DOMSubtreeModified` on the datepicker so you can inject your html code then.

It's a bit hacky but it might work well.

**Comment by reachtokish** [comment]
Thanks a lot for your kind information :+1:

**Comment by Azaret** [comment]
Brace yourself @reachtokish :)

**Comment by acrobat** [comment]
Closing this issue as #2043 was merged. The finishing touches for this feature (other beforeShow methods) will be done in #2120

**Comment by reachtokish** [comment]
ok
