### ISSUE TITLE
Update Multiple Dates programmatically not working

### ISSUE THREAD

**Issue by satyajit9830** [uxsolutions/bootstrap-datepicker#2038]
### Expected behaviour

I am storing expected selected dates in a variable. Then passing this variable to update dates, its not selecting dates.
### Datepicker version used

ex. 1.6.1.
### Example code

var dta = '"10/19/2016","10/20/2016"';
$('#datepicker').datepicker('update',dta);

**Comment by Azaret** [comment]
Give a try for:
```javascript
$('#datepicker').datepicker('update', '10/19/2016', '10/20/2016');
```

**Comment by jelhan** [comment]
Following documentation you should use `setDates` or `setUTCDates` methods.

**Comment by Azaret** [comment]
`update` does also work, it just expect an array of string and not a string.
The documentation should be more clear on this.
Gonna PR a change in few minutes.
