### ISSUE TITLE
defaultViewDate shows wrong month

### ISSUE THREAD

**Issue by wmlab03** [uxsolutions/bootstrap-datepicker#2051]
### Expected Outcome
When put defaultViewDate option, datepicker should show that date,month,year when opened.

### Actual Outcome
When put defaultViewDate option, datepicker shows next month date. In your demo also at https://uxsolutions.github.io/bootstrap-datepicker it is showing next month when this option is set. 

### Datepicker version used

ex. 1.6.4.

### See screenshot of demo
![datepicker-issue](https://cloud.githubusercontent.com/assets/15964546/19995198/2610d6ec-a27b-11e6-99b5-59ee11e29a67.png)

**Comment by Azaret** [comment]
Hi,
Yes it is not clearly stated in the documentation but it is implicitly with the example set at `0`, that the month parameter starts at zero.
