### ISSUE TITLE
today button wrong display with css body {display: "flex"} in chrome

### ISSUE THREAD

**Issue by NaturalL** [uxsolutions/bootstrap-datepicker#2093]
### Expected behaviour
.today with display:table-cell

### Actual behaviour
.today with display:block

### Datepicker version used

1.6.4.

### Example code

https://jsfiddle.net/zjmove/L43p8ek4/

It's because jquery
```
var a=$('<th>')
a.toggle(true)  
//output: <th style="display: block;"></th> wiht css body {display: "flex"} in chrome
```

**Comment by Azaret** [comment]
it is actually unfortunate to use display block on `th` since it is not a block, `table-cell` should be used instead.
