### ISSUE TITLE
Don't work correctly with yy formats

### ISSUE THREAD

**Issue by miklyha55** [uxsolutions/bootstrap-datepicker#2094]
Hello.

Thank you for a great work! Your datepicker is amazing, but I have one problem.

Date shown is not a correctly with format dd mm yy. I think it is not good. Please see the screenshot.
Can you tell me where is the problem in code? I can fix this problem in library.

Datepicker for Bootstrap v1.6.4

![screen](https://cloud.githubusercontent.com/assets/19971788/21418999/15c04878-c836-11e6-9694-c55540711b5b.PNG)

**Comment by naskobulgaria** [comment]
Same issue to me. Can someone help here please! Thank you !
I tryed this format "YY", but then datepicker show YY-01-13 for example. Does not show the full year.

**Comment by PlippiePlop** [comment]
I tested it in the demo but i can't replicate it.
![bs-164](https://cloud.githubusercontent.com/assets/728661/22368990/be703464-e489-11e6-9724-71065d213d69.JPG)

**Comment by mgbbs** [comment]
The problem is with parsing dates.  To reproduce on the demo site, change the format to m/d/yy, then type a date into the textbox, i.e. 2/3/17.  This issue exists in 1.6.4 as well at 1.7.0.  I'm going to have to roll back to an older version as I know this issue did not exist in 1.4.0.

**Comment by Azaret** [comment]
Yes, this is not a bug.  
The [`assumeNearbyYear`](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#assumenearbyyear) option have been introduce in order to allow user to selects years from 0 to 99.  
It was not possible before as when typing a 2-digits year result in appending current century to it.
