### ISSUE TITLE
Picker jumps to "today" and doesn't update after keyboard text entry when there are no separators in the format.

### ISSUE THREAD

**Issue by chilloutman** [uxsolutions/bootstrap-datepicker#210]
When using a format without separators like "yyyymmdd" the picker jumps to "today" instead of the date that is in the input field every time it gets focus.

The picker usually updates when the text in the input field changes. With a format that doesn't contain any separators that doesn't work either.

---

Assuming the date format "yyyy-mm-dd" and todays date it works as expected:
1. Select 2000-01-01
2. Leave the field
3. Click back on the field and the picker now shows the first of January 2000

With "yyyymmdd" and todays date this happens:
1. Select 2000-01-01
2. Leave the field
3. Click back on the field and the picker now shows the ninth of October 2012

---

Is there a problem with the date parsing?

**Comment by mickyp** [comment]
I found that seems this bug appears in 1.5.0, but didn't appear in 1.4.x.
