### ISSUE TITLE
Previous button issue when using template. 1.7.0-dev

### ISSUE THREAD

**Issue by PlippiePlop** [uxsolutions/bootstrap-datepicker#2113]
When using template for navigation buttons, for example font-awesome the previous month click adds months instead of contracting them. It only happens when adding template.

It also happens when selecting month and go back in months, and years

See example jsbin example. 
https://jsbin.com/zododogihe/edit?html,js,output

**Comment by vsn4ik** [comment]
Work fine for me: https://jsbin.com/geyowenuja/edit?html,js,output.

**Comment by PlippiePlop** [comment]
Your fiddle also has the same issue. select the first input and select previous month button. 
You will see the months count up instead of going down. 

To make sure I am not a fool, also tested it in Firefox, IE11 and Edge. Same issue.

**Comment by vsn4ik** [comment]
@PlippiePlop Indeed. I will correct this on next weekend.

**Comment by acrobat** [comment]
@vsn4ik I've added the release-1.7.0 again because I've already tagged 1.7.0-RC1 so this bug is already in 1.7.0

**Comment by vsn4ik** [comment]
@PlippiePlop fixed in current master and next release.

**Comment by acrobat** [comment]
Thanks @vsn4ik!
