### ISSUE TITLE
Can I revert to previous valid date when I input an invalid date?

### ISSUE THREAD

**Issue by Harry3014** [uxsolutions/bootstrap-datepicker#2125]
### Expected behaviour
I want to revert to previous valid date when I input an invalid date.

### Actual behaviour
I set 'forceParse' option to true, when I input an invalid date, it will be set to current date, it's not what I wanted.

**Comment by prad9** [comment]
I have similar issue but would like to keep the invalid date as is without changing it so that i can show the error message to user for correction.
Similar to: http://eonasdan.github.io/bootstrap-datetimepicker/Functions/#keepinvalid
