### ISSUE TITLE
Cannot run: datepicker is not a function

### ISSUE THREAD

**Issue by MurKit** [uxsolutions/bootstrap-datepicker#2126]
Cannot make it run.

On page load I have this errors in the console.

jQuery.Deferred exception: $(...).datepicker is not a function @http://127.0.0.1:8000/js/datepicker_config.js:2:5
g/</j@http://127.0.0.1:8000/js/jquery.js:2:29946
g/</k<@http://127.0.0.1:8000/js/jquery.js:2:30262
 undefined  jquery.js:2:31515

TypeError: $(...).datepicker is not a function[Learn More]  datepicker_config.js:2:5

Datepicker version used. 1.6.4

This all is included like that 
    <script type="text/javascript" src="{{ asset('js/jquery.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap.js') }}"></script>

    <script type="text/javascript" src="{{ asset('js/bootstrap-datepicker.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/datepicker_config.js') }}"></script>

I am using Laravel.

**Comment by Azaret** [comment]
Well it looks like the file is not loaded at all, and not thing to do with the lib.  
You should check if the path to the file is right, if the file is actually here, etc;...

**Comment by MurKit** [comment]
But I see that the file is loaded. It has 200 response.
