### ISSUE TITLE
data attributes not working with input groups?

### ISSUE THREAD

**Issue by KrunchMuffin** [uxsolutions/bootstrap-datepicker#2133]
### Expected behaviour
data attributes should work

### Actual behaviour
data attributes not working

### Datepicker version used

v1.7.0-dev

### Example code

https://jsfiddle.net/hewhy2mm/15/

**Comment by KrunchMuffin** [comment]
nevermind. had start-week instead of week-start

**Comment by KrunchMuffin** [comment]
I lied, it still does not work with input-group

https://jsfiddle.net/hewhy2mm/16/

**Comment by vsn4ik** [comment]
Use `<div class="input-group date ..." data-date-week-start="1">`.
I will add a clarification in the documentation on the following weekend.

**Comment by KrunchMuffin** [comment]
Thanks, that works.
