### ISSUE TITLE
Year navigation

### ISSUE THREAD

**Issue by lcsqlpete** [uxsolutions/bootstrap-datepicker#2135]
I might be missing something but I don;t see a way to and navigation arrows that move back/forward a year at a time as well as the arrows that move the month.  Is this possible?

**Comment by Azaret** [comment]
You just need to hit the month name on top of the picker, then you can go from one year to another.  
![](http://g.recordit.co/Y2mhVGEpO3.gif)

**Comment by lcsqlpete** [comment]
Right, thanks, I figured that out after posting.  It's just a somewhat
unusual user interface compared to most other datepickers that just have
navigation arrows that move forward and backward by a year,
