### ISSUE TITLE
can any one help how to allow manual input date in this plugin

### ISSUE THREAD

**Issue by dhanarajp** [uxsolutions/bootstrap-datepicker#2138]
### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Datepicker version used

ex. 1.6.1.

### Example code

Jsfiddle example to reproduce the problem.

**Comment by acrobat** [comment]
@dhanarajp in the GitHub repository we only discuss bugs and new features. For this kind of questions please use any of the support alternatives like [gitter](https://gitter.im/eternicode/bootstrap-datepicker) or [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker) Thanks!

Also providing at least a bit of code to show us what you already have tried, as will speed up the process of finding a solutions for your problem.
