### ISSUE TITLE
datepicker is missing

### ISSUE THREAD

**Issue by GioMBG** [uxsolutions/bootstrap-datepicker#2155]
### Expected behaviour
I don't understand how I have to call in header to make datepicker visible in my form

### Actual behaviour
datepicker not appear

### Datepicker version used

ex. 1.6.1.

### Example code

Jsfiddle example to reproduce the problem.

**Comment by acrobat** [comment]
@GioMBG  in the GitHub repository we only discuss bugs and new features. For this kind of questions please use any of the support alternatives like [gitter](https://gitter.im/eternicode/bootstrap-datepicker) or [stackoverflow](http://stackoverflow.com/questions/tagged/bootstrap-datepicker) Thanks!

But to get you started here is [an example](http://jsfiddle.net/zcvq0yhh/215/) and [here are the docs](https://bootstrap-datepicker.readthedocs.io/en/stable/)
