### ISSUE TITLE
Bootstrap-datepicker does not display right

### ISSUE THREAD

**Issue by handsomeyao77** [uxsolutions/bootstrap-datepicker#2156]
![image](https://cloud.githubusercontent.com/assets/7311188/24494127/c0fe4c60-1563-11e7-8255-edf358ae86f6.png)

I just added the bootstrap-datetimepicker.css, any one knows about this issue?

**Comment by acrobat** [comment]
HI @handsomeyao77 

This is the bootstrap-datepicker repository. If you want support for bootstrap-datetimepicker you should create an issue in [that repository](https://github.com/Eonasdan/bootstrap-datetimepicker)
