### ISSUE TITLE
Branch

### ISSUE THREAD

**Issue by DavidDecraene** [uxsolutions/bootstrap-datepicker#2169]
Is there any explanation on why you branched from https://eonasdan.github.io/bootstrap-datetimepicker/ and what the possible differences or Pro/contras are?

Greetings

**Comment by acrobat** [comment]
Hi @DavidDecraene,

We didn't branch off from the bootstrap-datetimepicker. If I remember correctly it was the other way around (but a long time ago).

Off course the main difference is that we don't have time support and they have. For other feature differences you should look at the documentation of each library to find specific differences.
