### ISSUE TITLE
Jquery later append  how to trigger？

### ISSUE THREAD

**Issue by fuerpeng** [uxsolutions/bootstrap-datepicker#2184]
### Expected behaviour
Tell us what should happen.

### Actual behaviour
Tell us what happens instead.

### Datepicker version used

ex. 1.6.1.

### Example code

Jsfiddle example to reproduce the problem.
![image](https://cloud.githubusercontent.com/assets/24818415/25929770/ddbf413c-3634-11e7-9270-4ffedbac486c.png)
  I use this method, but append to the first trigger can not. what can i do?

**Comment by acrobat** [comment]
HI @fuerpeng 

This is the bootstrap-datepicker repository. It looks like you need support for bootstrap-datetimepicker, you should create an issue in [that repository](https://github.com/Eonasdan/bootstrap-datetimepicker)

**Comment by fuerpeng** [comment]
i am sorry

**Comment by acrobat** [comment]
No problem! Good luck finding a solution!
