### ISSUE TITLE
language setting is useless

### ISSUE THREAD

**Issue by dataparker** [uxsolutions/bootstrap-datepicker#2186]
### Expected behaviour
Tell us what should happen.
After adding the zh-CN.js to my file the date form should be in Chinese.
### Actual behaviour
Tell us what happens instead.
No change,still in English.
### Datepicker version used

ex. 1.6.1.

### Example code

Jsfiddle example to reproduce the problem.

**Comment by acrobat** [comment]
This looks like more of a problem with your code. Here's is an example with the included locale file and correct language setting: http://jsfiddle.net/zcvq0yhh/262/

Closing this for now.
