### ISSUE TITLE
Out of stack space (Error 28) - Internet explorer 11, 10, 9 Crashing application 

### ISSUE THREAD

**Issue by samir-kamble** [uxsolutions/bootstrap-datepicker#2202]
![untitled](https://user-images.githubusercontent.com/12523579/26967979-f3790ac6-4d1d-11e7-8a05-b4b50de95359.png)

### Expected behaviour
I have an interface where we add tabs dynamically to the system and content is being rendered via AJAX. Inside which I am using datepicker.  

### Actual behaviour
It worked well for Chrome and Firefox when adding and rendering tab content via AJAX. But in IE it works in first go and on 2nd generated tab it gives this error.
> Out of stack space (Error 28)

### Datepicker version used
1.6.4, tested with 1.7.0 RC3 as well

### Example code
$('.datepicker').datepicker({
        autoclose: true,
        endDate: "-infinity",
        format: "dd-M-yyyy"
      });

Cannot produce JSfiddle as the tabs framework is very big.

**Comment by vuongmn** [comment]
Hi All,

I've the same issue.
But when I upgrade to version 1.7.1. The bug was fixed. But I don't see in in Changelog of version 1.7.1?

Regards,

**Comment by samir-kamble** [comment]
It was causing because of JqueryUI. I removed it and it started working fine.
