### ISSUE TITLE
The appearance of datepicker on mobile is broken

### ISSUE THREAD

**Issue by iloveip** [uxsolutions/bootstrap-datepicker#2207]
UPD: This should be closed.

**Comment by acrobat** [comment]
Hi @iloveip, thanks for the bug report! Can you provide a jsfiddle to replicate the problem?

**Comment by iloveip** [comment]
@acrobat The problem is in the datepicker-dropdown. Is it possible to replicate it in jsfiddle? (I've tried, but I can get only an embedded version.)

**Comment by iloveip** [comment]
@acrobat I'm sorry for the trouble, the problem was in my css file.
