### ISSUE TITLE
Feature Request:  config option datesEnabled

### ISSUE THREAD

**Issue by dkent600** [uxsolutions/bootstrap-datepicker#2208]
Would be great if I could have a property `datesEnabled` that would behave the opposite of `datesDisabled`!

It is not feasible to disable every date going infinitely into the future.  I may only have a two week-long period in which there are just 4-5 enabled dates.

Thanks.

**Comment by dkent600** [comment]
I'm going to close this because I think with the combination of all the other config settings I can get what I want.

**Comment by omarpiani** [comment]
uh, how? its possible you need thousands of disabled elements!
