### ISSUE TITLE
ng test: Uncaught TypeError: Cannot set property 'de' of undefined

### ISSUE THREAD

**Issue by SrAxi** [uxsolutions/bootstrap-datepicker#2213]
### Expected behaviour
When executing `ng test` command, it should not throw library involved errors, but it should proceed with the Karma test cases.

### Actual behaviour
It throws the following error:

> Chrome 59.0.3071 (Windows 10 0.0.0) ERROR
>   Uncaught TypeError: Cannot set property 'de' of undefined
>   at webpack:///~/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js:1:0 <- src/test.ts:124812
> 
> Chrome 59.0.3071 (Windows 10 0.0.0) ERROR
>   Uncaught TypeError: Cannot set property 'de' of undefined
>   at webpack:///~/bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js:1:0 <- src/test.ts:124812
> 

I would like to point out that when executing `ng serve` it works perfectly, I encounter issues just when testing.

### Datepicker version used

^1.7.0.

### Example code

This is where I'm importing the library:
**Module:**

```
import 'bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js';
import 'bootstrap-datepicker/dist/css/bootstrap-datepicker3.min.css';

import { NKDatetimeModule } from 'ng2-datetime/ng2-datetime';

import 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.de.min.js';
import 'bootstrap-datepicker/dist/locales/bootstrap-datepicker.es.min.js';
```
I added this code to **`karma.conf.js`** in order to avoid jQuery UI issues that I encountered previously:

```
files: [
	{pattern: './node_modules/jquery-ui-npm/jquery-ui.min.js', watched: false},
	{pattern: './src/test.ts', watched: false}
],
```

**Comment by SrAxi** [comment]
Finally fixed it!

I added to **`karma.conf.js`** this:

`{pattern: './node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js', watched: false},`

The final `files` array is like this:

```
files: [
	{pattern: './node_modules/jquery-ui-npm/jquery-ui.min.js', watched: false},
	{pattern: './node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js', watched: false},
	{pattern: './src/test.ts', watched: false}
],
```

**Comment by acrobat** [comment]
@SrAxi Good to hear you've been able to fix the problem!
