### ISSUE TITLE
Problem using datepicker in Bootstrap Modal

### ISSUE THREAD

**Issue by lcsqlpete** [uxsolutions/bootstrap-datepicker#2232]
I am loading data into a BS3 modal at the show.bs.modal event, including a datepicker control. When I click the control to bring up the datepicker and every time I click on a date within it, the show.bs.modal event fires.

How can I avoid this?

**Comment by danihuge** [comment]
same to me, thanks!

**Comment by danihuge** [comment]
@lcsqlpete I fixed with: 
modal.on('show.bs.modal', function(e) {
    if (e.namespace === 'bs.modal') {
        //
    }
});

**Comment by lcsqlpete** [comment]
Thanks, that worked for me also.
