### ISSUE TITLE
Events not triggering in multidate picker

### ISSUE THREAD

**Issue by claudiagoga** [uxsolutions/bootstrap-datepicker#2245]
### Expected behaviour
I have a datepicker with multidate, and I want show the number of dates selected, when the user selects dates from the picker.

### Actual behaviour
It seems that my picker won't fire events, below is the code. Can you help me figure out how to make it work?

### Datepicker version used

version is 1.7.1.

### Example code

```
<div class=" input-group date form-group" id="datepicker">
 <input type="text" class="form-control" id="Dates" name="Dates" placeholder="[[[Select days]]]" required />
  <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
</div>

$(document).ready(function () {
        $('#datepicker').datepicker({
            startDate: new Date(),
            multidate: true,
            format: "dd/mm/yyyy",
            daysOfWeekHighlighted: "5,6",
            @*datesDisabled: [@Html.Raw(datesDisabled.ToString())],*@
            language: '@Context.GetPrincipalAppLanguageForRequest().ToString()'
        }).on('changeDate', function (e) {
            // `e` here contains the extra attributes
            console.log( "aaa")
        });
    });
```

**Comment by christianklemp-imt** [comment]
Seems to be working fine for me. See this JSFiddle on how I got it working: https://jsfiddle.net/christianklemp_imt/b20paum2/

**Comment by claudiagoga** [comment]
Thanks. It works now.

I was updating the jquery in the wrong place. The picker was in a modal dialog. My bad :)
