### ISSUE TITLE
Couldn't go back to last year in months view mode

### ISSUE THREAD

**Issue by tungox6** [uxsolutions/bootstrap-datepicker#2260]
In the months view mode, when you click on the previous year button, the next year button is still hidden.

My settings:
``
            format: "mm-yyyy",
	    viewMode: "months",	    
	    minViewMode: "months",	    
	    startDate: '-60y',
	    endDate: new Date(),	    
	    autoclose: true,
``

### Datepicker version used

1.7.1.

**Comment by vsn4ik** [comment]
@tungox6 Thanks!
Please, check your problem on https://codepen.io/anon/pen/jGzowm?editors=1010.

**Comment by vsn4ik** [comment]
Fixed by #2352
