### ISSUE TITLE
"Next button" is hidden on month picker mode

### ISSUE THREAD

**Issue by ScriptArtist** [uxsolutions/bootstrap-datepicker#2283]
### Expected behaviour
When clicked on the "Previous year" button, the button "Next year" should be displayed.

### Actual behaviour
"Next year" button is hidden.

### Datepicker version used
1.7.1. - bug reproducible 
1.6.1 - expected behavior

### Example code
$(el).datepicker({
      minViewMode: 1,
      maxViewMode: 2,
      startDate: "01.01.2013",
      endDate: "today"
    });

Jsfiddle example: https://jsfiddle.net/6rkmp685/

**Comment by kwagdy** [comment]
Check here https://github.com/uxsolutions/bootstrap-datepicker/issues/2266 :)

**Comment by vsn4ik** [comment]
Fixed by #2352.
