### ISSUE TITLE
Weird bug

### ISSUE THREAD

**Issue by Sjoerrdd** [uxsolutions/bootstrap-datepicker#2304]
### Expected behaviour
Tell us what should happen.
I want to pick a date, but it goes wrong. (https://gyazo.com/a2c55486e35088525393edd691390068)
I'm using the latest version of datepicker

Code:
```
      $('.datepicker').datepicker({
          format: 'yyyy-mm-dd',
      });
```

**Comment by pyprism** [comment]
Recently same bug hit me . In my case I changed the input type `date`  to  `text` .

**Comment by pankaj7590** [comment]
same issue even when type is text, the actual value is not set until set explicitly using datepicker's function
