### ISSUE TITLE
Nuget version is 2 yrs old 2016 ver 1.6

### ISSUE THREAD

**Issue by weedkiller** [uxsolutions/bootstrap-datepicker#2321]
Hello can you please release an update to 1.7.1
currently the ASP solutions dont see 171, just [1.6](https://www.nuget.org/packages/Bootstrap.Datepicker/)

**Comment by acrobat** [comment]
Please contact @scott-xu (see the nuget detail page for the link) as he maintains the nuget packages. We only "support" (read maintain) the composer, npm and bower package.

**Comment by scott-xu** [comment]
updated @weedkiller

**Comment by mrlife** [comment]
@scott-xu Would it be possible to have the NuGet package updated to 1.8?

**Comment by scott-xu** [comment]
updated @mrlife
