### ISSUE TITLE
Right arrow disappear after going back a year

### ISSUE THREAD

**Issue by italoborges** [uxsolutions/bootstrap-datepicker#2353]
Hello!

### Expected behaviour

I have two datepicker fields for start date and end date. 
For both fields, I set a max date. 

### Actual behaviour

When I open the datepicker for each field, it shows me the year of 2018 and the month February, when I click to the arrow to go to the year of 2017, the right arrow to return to the year of 2018 disappear (disabled).

### Datepicker version used

1.7.1.

### Bootstrap version used

4.0.0.

### JQuery version used

3.2.1.

### Example code

https://jsfiddle.net/italoborges/kvtw6Lby/

Thanks!

**Comment by aaronkondziela** [comment]
I have this same problem with datepicker 1.7.1 and bootstrap 4.0.0 and jquery 3.3.1

I installed 1.6.4 and it works.

**Comment by italoborges** [comment]
@aaronkondziela , it worked! Thanks!

**Comment by siruguri** [comment]
We found that _upgrading_ to 1.8.0 also worked for us. Our dependencies: bootstrap 3.3.7; jquery 1.12.4

**Comment by vsn4ik** [comment]
Fixed in #2352.
