### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by archistico** [uxsolutions/bootstrap-datepicker#2359]
### Expected behaviour
This datepicker is compatible with Bootstrap 4?

**Comment by tiesont** [comment]
Yes.

**Comment by tomsommer** [comment]
See https://github.com/uxsolutions/bootstrap-datepicker/issues/1574

**Comment by teoSalvetti** [comment]
I'm trying to use the version 1.7.1 but with boostrap 4 it doesn't work..
So which version should I use?

**Comment by tiesont** [comment]
@teoSalvetti I'm using 1.7.1 with Bootstrap 4 and it works just fine. Is there some specific problem you're running into?

**Comment by teoSalvetti** [comment]
@tiesont my mistake! I'll delete the previous comment

**Comment by archistico** [comment]
Thank you

**Comment by X-Coder** [comment]
Hi, is this really bootstrap 4 compatible?
I'm asking because there is version restriction in composer.json:
`"components/bootstrap" : ">=2.0, <4.0",`

I think the this version constraint should be updated if its compatible.
