### ISSUE TITLE
Datepicker doesn't hide after selecting date

### ISSUE THREAD

**Issue by geaden** [uxsolutions/bootstrap-datepicker#236]
When I select date datepicker is still on my screen, when I click anywhere on page it disappears. I tried to use 'changeDate', but when I click today button datepicker disappears with no date selection

**Comment by fernandoGN** [comment]
For me, this was the solution:
```javascript
$('selector').datepicker().on('changeDate',function(e) {
	$('selector').datepicker('hide');
});
```

**Comment by pjammer** [comment]
@fernandoGN thanks! worked for me in the latests jquery and bootstrap-datepicker

**Comment by divinedragon** [comment]
Anybody who is struggling with datepicker not closing when the date is selected in a modal window, can use the following fix.
Here is the issue demo on jsFiddle - http://jsfiddle.net/R9AT2/1/
Here is the fix demo on jsFiddle - http://jsfiddle.net/divinedragon/R9AT2/87/

The trick is to set the focus back to modal div.

    $("#datepicker").datepicker({
        onSelect: function() {
            $("#dialog").focus();
        }
    });
    $("#dialog").dialog({
        modal: true
    });

**Comment by sergiopedraza** [comment]
@divinedragon your fix does not work in IE. The datepicker is always present

**Comment by hirenpatel29** [comment]
Hello EveryOne,

I have made bootstrap 4 datetimepicker control in asp.net c#. When I am using date only in format then my datetime picker works perfectly but when I added in time format with date then my datetime picker is not closing after selecting datetime. I have tried all suggestions mentioned above. Please help me out.

[bootstrap-datetimepicker.min.txt](https://github.com/uxsolutions/bootstrap-datepicker/files/4975972/bootstrap-datetimepicker.min.txt)

ascx page :
<%@ Control Language="C#" AutoEventWireup="true" CodeFile="DateTimePicker.ascx.cs" Inherits="Assets_UserControl_DateTimePicker" %>
<div class="input-group">
    <div class="input-group-prepend" runat="server" Visible="False" id="divPrepend" ClientIDMode="Static">
        <label class="input-group-text" runat="server" id="lblPrepend" ClientIDMode="Static">Date :</label>
    </div>
    <asp:TextBox type="text" ID="TextBox1" runat="server" CssClass="form-control datepicker" ClientIDMode="Static"  placeholder="Date" />
</div>

ascx.cs page
 private string _sFormat = "MM/DD/YYYY HH:mm:ss";    
    
    public string sFormat
    {
        get { return _sFormat; }
        set { _sFormat = value; }
    }
Page Load :
string s = @"<script type=text/javascript> $(function () { $('#" + sTextBoxID + "').datetimepicker({ format: '" + sFormat + "' });});</script>";
        //string s = @"<script type=text/javascript>$( document ).ready(function() {$('#" + sTextBoxID + "').datetimepicker({ format: '" + sFormat + "' }).on('changeDate', function(ev){$(this).datetimepicker('hide');});});</script>";
        //string s = @"<script type=text/javascript>$(document).ready(function () {$('#" + sTextBoxID + "').datepicker().on('change.datetimepicker', function(ev){alert('hi');$('.datepicker').hide();});})</script>";
        
        Page.ClientScript.RegisterClientScriptBlock(GetType(), "dtsc_" + sTextBoxID, s, false);
        if (!string.IsNullOrEmpty(Attributes["placeholder"])) TextBox1.Attributes["placeholder"] = Attributes["placeholder"];
        if (!String.IsNullOrEmpty(sLabelText))
        {
            divPrepend.Visible = true;
            lblPrepend.InnerText = sLabelText;
        }

**Comment by BilalNazir123** [comment]
$('#id_of_your_field').datepicker({
        autoclose: true
        });
