### ISSUE TITLE
Next button still enabled in month that contains endDate

### ISSUE THREAD

**Issue by adrx** [uxsolutions/bootstrap-datepicker#2364]
### Expected behaviour
Tell us what should happen.

In days view, in the month that contains the endDate the next arrow should be disabled (i.e., not appear)

### Actual behaviour
Tell us what happens instead.

In version 1.8.0, the next button is enabled when the month that contains the endDate is displayed. Clicking on it displays the month after the month that contains the endDate.

### Datepicker version used

1.8.0
Works as it should in version 1.7.1

### Example code

Jsfiddle example to reproduce the problem.
https://jsfiddle.net/xpvt214o/75874/

**Comment by vsn4ik** [comment]
Fixed in #2352.
