### ISSUE TITLE
startDate and endDate bug

### ISSUE THREAD

**Issue by aungkyawhein** [uxsolutions/bootstrap-datepicker#2385]
### Working on v1.7.1 and older versions
Navigation arrow for previous month should not show when startDate is set. (Same for endDate and next month.)

### Issue on v1.8.0
Navigation arrow for previous month is showing when startDate is set to today. (Same for endDate and next month.) Still can navigate to previous month although all the dates are not available.

### Datepicker version
1.8.0

### Example on v1.7.1
https://codepen.io/aungkyawhein/pen/erVqGZ

### Example on v1.8.0
https://codepen.io/aungkyawhein/pen/JvpgwM

**Comment by Nex4rius** [comment]
I had the same problem when trying to set the startDate so I fixed it :)
