### ISSUE TITLE
Possible XSS in data-date-container attribute

### ISSUE THREAD

**Issue by 1Jesper1** [uxsolutions/bootstrap-datepicker#2390]
### Expected behaviour

> Data-date-container

 should use jQuery find method to find the selector instead of placing it right away in the jQuery selector

### Actual behaviour
Text is placed in jQuery selector as element, so the element is created and the XSS is performed.

### Datepicker version used

1.8.0

### Example code

https://jsfiddle.net/rsvnyf9a/

PS: https://uxsolutions.github.io/bootstrap-datepicker/ Demo page sandbox-js element is vulnerable for XSS, because the html is loaded straight into the pre element. Just type `<img src=1 onerror=alert(123) />` into an input.

**Comment by Tea56** [comment]
@1Jesper1 

Good catch. 
Btw, bootstrap 3.4.0-dev branch has patched the issue. they missed it on tabs, but the rest is patched.

**Comment by 1Jesper1** [comment]
@Tea56 Yes, also on tabs I see. They have fixed it in v4-dev (v4.1.2) also now.

**Comment by rjoshi18** [comment]
@1Jesper1 
Could You please provide us here with the exact fix in the Github.
Thanks

**Comment by 1Jesper1** [comment]
@rjoshi18 https://github.com/uxsolutions/bootstrap-datepicker/blob/2a54f44e54ea7c3ac7bfdf7d42801535e56ad2a1/js/bootstrap-datepicker.js#L674
This is the line I think where the Jquery find method should be used, like https://github.com/twbs/bootstrap/pull/23679/commits/2ba83171807bdec8ce5235042e6abfc6906a1d09

See my JSFiddle: If you provider the XSS to the `Data-date-container` attribute the XSS will trigger.

**Comment by kendallli** [comment]
@Tea56 Is there any need we need to fix it in the bootstrap-datepicker.js file? I found that the line `container = $(this.o.container)` is the same in v1.9. I am currently using v1.7.3.

**Comment by 1Jesper1** [comment]
@rjoshi18 @kendallli  has this been fixed?

**Comment by 1Jesper1** [comment]
Can't seem to reproduce this anymore.
