### ISSUE TITLE
CSS files now going into Contents folder rather than Content folder

### ISSUE THREAD

**Issue by erwin42** [uxsolutions/bootstrap-datepicker#2418]
### Expected behaviour
Upgraded to 1.8.0.

CSS files should go to **Content** folder.

### Actual behaviour
CSS files now going to **Contents** folder. Is this intentional?

Version 1.8.0

### Example code

N/A

**Comment by IronRabbitxx** [comment]
The same here.
![image](https://user-images.githubusercontent.com/1189951/44724764-f7fa5680-aad3-11e8-8bf0-9cb9bb0215f5.png)

**Comment by tmccoid** [comment]
This remains an issue as of Nov 7.  I updated a web project in Visual Studio 2017 through NuGet to use 1.8.0; the previous files in the Content directory were removed and the updated files were placed in a new Contents directory.

**Comment by omarpiani** [comment]
ye, it's a nuget problem, no nuspec file is versioned in order to make a PR for this

**Comment by acrobat** [comment]
We don't actually manage/provide the nuget package. @scott-xu created the nuget package, so I ping him to take a look at this issue.

**Comment by scott-xu** [comment]
fixed

**Comment by acrobat** [comment]
Thanks @scott-xu!
