### ISSUE TITLE
Add 'input-group-append' to catch up with bootstrap 4

### ISSUE THREAD

**Issue by asbayer** [uxsolutions/bootstrap-datepicker#2436]
### Expected behaviour
Make the datepicker work again by adding ', .input-group-append' to line 118 in the file bootstrap-datepicker.js.
this.component = this.element.hasClass('date') ? this.element.find('.add-on, .input-group-addon, **.input-group-append**, .btn') : false;

### Actual behaviour
Datepicker is not working with boostrap 4 input-group when input-group-addon is used.

### Datepicker version used
Whatever I got from NuGet this morning. I guess it was called 1.8

**Comment by DianaKoenraadt** [comment]
For anyone visiting whie it's not incorporated in the .js yet, another workaround is to add the class ".add-on" in your HTML

**Comment by DianaKoenraadt** [comment]
@wimdeblauwe This is an excerpt my HTML:

    <div class="input-group date">
        <input ...... >
        <div class="input-group-append add-on">
            ......
        </div>
    </div>

Basically, instead of adding the class that is missing (input-group-append) to the JavaScript, I add one that it *does* know to my HTML

**Comment by asbayer** [comment]
Ok... I will use the class `add-on`. 
Thank you.

**Comment by wimdeblauwe** [comment]
Does not seem to work for me using Bootstrap 4. What "version" of the CSS are you using?
