### ISSUE TITLE
Can't get calendar to appear on click - no JS errors

### ISSUE THREAD

**Issue by garyhooks** [uxsolutions/bootstrap-datepicker#2461]
**I have this in <head>:**

```
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>

 <script type="text/javascript"> 
$('#datetimepicker input').click(function(event){
   $('#datetimepicker ').data("DateTimePicker").show(); 
});
    </script>
```

**In body I have:**

```
<div class="input-group">
    <input type="text" id="datetimepicker" class="form-control" name="date">
    <label class="input-group-addon btn" for="date">
       <span class="fa fa-calendar open-datetimepicker"></span>
    </label>
</div>

```

**No errors**

There are no javascript errors
I have installed everything I should do I think, using yarn but still I can't get the calendar to pop up?

I've been searching endless online and trying different solutions but with no success.

Can any advise?
Thanks

**Comment by garyhooks** [comment]
Anyone?

**Comment by Jojo67** [comment]
Did you initialise it in the page load? Something like $('.input-group').datepicker({..your params.});

If its been initialised it should automatically appear when the input field is clicked - you shouldn't need to capture the click event or execute show().

**Comment by thmasker** [comment]
> Did you initialise it in the page load? Something like $('.input-group').datepicker({..your params.});
> 
> If its been initialised it should automatically appear when the input field is clicked - you shouldn't need to capture the click event or execute show().

Hello, I think I have the same problem, and I would like you to explain a little more about the "initialise it in the page load" thing... In what part of the code should I put that? Thanks
