### ISSUE TITLE
data-date-langauge does not work?

### ISSUE THREAD

**Issue by EugenMayer** [uxsolutions/bootstrap-datepicker#2467]
### Expected behaviour
switching language using data attribute `data-date-langauge`

### Actual behaviour
Does not work, it is ignored, i have to use it as parameter to `datepicker()` instead

so the workarround for me is right now more or less

`$datepickerContainer.datepicker({language: $datepickerContainer.data('date-language')})`

### Datepicker version used
1.8.0

**Comment by ocarreterom** [comment]
@EugenMayer try v1.9.0
Works as expected in this example: https://jsfiddle.net/31c98qjr/
