### ISSUE TITLE
Hard to use. Bad explanation.

### ISSUE THREAD

**Issue by SoltauFintel** [uxsolutions/bootstrap-datepicker#2471]
Please write a better explanation how to use the Bootstrap datepicker.

**Comment by Sauedy** [comment]
@SoltauFintel the documentation is straightforward:

https://bootstrap-datepicker.readthedocs.io/en/latest/

**Comment by SoltauFintel** [comment]
Please supply a **simple** example.

- e.g. a page just with "$('.datepicker').datepicker();" does not work.
- What .js, .css files do I need?
- What HTML do I need?
- What do I need for localization? Did not work including the language file.
- Do I need the "less" stuff?
- Is there a troubleshooting guide? What if I press the button and 2 calendars appear?

There's so much stuff on the documentation page. I don't need thousand config options if I cannot get the simple case running. It's just a datepicker. It should not be so difficult to use. And not everybody is a JavaScript pro.

A **simple** example would be great.

**Comment by Sauedy** [comment]
@SoltauFintel I do understand. The documentation list the following two components/library as requirements: 

1. [Bootstrap 2.0.4+](https://getbootstrap.com/docs/3.3/getting-started/#download)
2. [jQuery 1.7.1+](https://code.jquery.com/jquery-3.3.1.min.js)

The links point to the latest version of each.

You then need to download the datepicker .css and .js file, below are the link for each:

1. [bootstrap-datepicker.min.css v1.8.0](https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css)
2. [bootstrap-datepicker.min.js v1.8.0](https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js)

You can either download these files or use the links.

This is a working example on [jsfiddle](https://jsfiddle.net/Sauedy/qh0L1tzc/).

Once on the jsfiddle demo, click **Resources** on the left menu to look at the order the files are being referenced. 

If you are having difficulties following this, I will strongly recommend you read the **bootstrap** documentation and then read the **datepicker** documentation, it will benefit you at the end.

Hope that helps. :)

**Comment by Sparragus** [comment]
Wow @SoltauFintel. Your tone is horrible and commanding. This is open source. Send a PR.

**Comment by benlawraus** [comment]
@SoltauFintel Have you seen the explanation here?
[](https://www.jqueryscript.net/time-clock/Configurable-Date-Picker-Plugin-For-Bootstrap.html)
