### ISSUE TITLE
Datepicker issue with Date Range

### ISSUE THREAD

**Issue by smit-devdigital** [uxsolutions/bootstrap-datepicker#2473]
Hi

In the below scenario Date Range is not working correctly for Bootstrap Datepicker:
Step 1: Select Start Date E.g. 04/01/2019 so by default datepicker set 04/01/2019 date as the End Date.
Step 2: Now Clear Start Date using Clear Button. E.g Clear 04/01/2019 from Start Date.
Step 3: No select different Start Date which is greater than End Date E.g.  Select 04/05/2019 as Start Date. So End should get updated to 04/05/2019. But it is not working. If select 04/05/2019 as Start Date again then it is working.

See Below Video:
https://drive.google.com/file/d/1pPfQhwCxoZLeaDG_zAy8l6qhQr1JGMSZ/view

Thank You

**Comment by johnnyRose** [comment]
I reproduced this in a fiddle: https://jsfiddle.net/johnnyRose/okewcnpm/18/

Click the "Problem 2" button to reproduce.

**Comment by smit-devdigital** [comment]
Thank You @johnnyRose for fixing the issue. I verified the issue it is working fine.

Thank You

**Comment by johnnyRose** [comment]
@smit-devdigital glad it works for you! You might consider leaving the issue open until the PR is merged, however - that way we don't lose track of it while we are waiting for the merge. :)
