### ISSUE TITLE
jQuery update to version 3.4.1 breaks bootstrap-datepicker

### ISSUE THREAD

**Issue by jodydeanrogan** [uxsolutions/bootstrap-datepicker#2486]
### Expected behaviour
datepicker is defined on jQuery elements

### Actual behaviour
datepicker is no longer defined on jQuery elements after jQuery is upgraded to 3.4.1

### Datepicker version used
1.8.0

### Example code

Jsfiddle example to reproduce the problem.

**Comment by vsn4ik** [comment]
[Online Demo](https://uxsolutions.github.io/bootstrap-datepicker) working perfectly with `jQuery@3.4.1`

**Comment by ArtturiSipila** [comment]
I have the same issue. Went back to our previous version of Jquery (3.3.1) and it's working again.

**Comment by aducom** [comment]
Did not try that but tried to include the same version as the sample here. This is my trace:
![afbeelding](https://user-images.githubusercontent.com/5610893/63435565-722f9380-c427-11e9-9c00-6637a6f0c311.png)

**Comment by aducom** [comment]
Why is this closed? The issue still persists...

**Comment by vsn4ik** [comment]
https://github.com/uxsolutions/bootstrap-datepicker/blob/master/CONTRIBUTING.md#issues
> A working example of the bug you've found is much easier to work with than a description alone. If possible, please provide a link to a demonstration of the bug, perhaps using https://jsfiddle.net/.

**Comment by aducom** [comment]
Fair enough. I found out that using the libs external do work here, but I have an issue with hosting the libs locally with the application. Must be something on my side. Sorry having bothered you.
