### ISSUE TITLE
Uncaught TypeError: Cannot read property 'top' of undefined 

### ISSUE THREAD

**Issue by joelkinzel** [uxsolutions/bootstrap-datepicker#249]
Using the latest version of the datepicker I'm getting this error. Following my code: 

```
<div class="control-group">
    <label class="control-label" for="question-15">Start Date:</label>  
    <div class="controls">
        <input type="text" name="start_date[response]" value="" id="question-15" class="required date">
    </div>
</div>
<div class="control-group">
    <label class="control-label" for="question-16">End Date:</label>    
    <div class="controls">
        <input type="text" name="end_date[response]" value="" id="question-16" class="required date">
    </div>
</div>
<script>
$(function(){
    $('.date').datepicker();
});
</script>
```

When I attempt to do this, I'm getting the following error: 
Uncaught TypeError: Cannot read property 'top' of undefined in bootstrap-datepicker.js on line 148

**Comment by grandmanitou** [comment]
Same problem for me. But it's solved. 
I had to change my input's classname from 'form-control date' to 'form-control form-date' to make it work.

**Comment by GabrieleMartini** [comment]
Same issue for jQuery v1.10.1 , and same solution: using class different than 'date' make it working.
