### ISSUE TITLE
2 separate Date-pickers without using Range

### ISSUE THREAD

**Issue by JZwanepoel1996XD** [uxsolutions/bootstrap-datepicker#2495]
### Expected behavior
Hi everyone, This is probably a noob question but I'm trying to use 2 separate date pickers, and when the startDatePicker's date is selected the endDatePicker should have a startDate option with the date of the selected startDatePicker and then same with endDate it should then limit the EndDate.

### Datepicker version used
ex. 1.6.1.

**Comment by Azaret** [comment]
Hi, You can easily do so with the [`beforeShowDay`](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#beforeshowday) callback.
Here's a snippet: https://jsfiddle.net/azaret/25bqa6ho/
