### ISSUE TITLE
Unable setDate as max date programatically

### ISSUE THREAD

**Issue by conangithub** [uxsolutions/bootstrap-datepicker#2505]
Hello. When set the date value in bootstrap-datepicker as max date limit, it's not display anything.

Here is my code.

```
$('.start_date')
    .datepicker({format: "yyyy-mm-dd"})
    .on('changeDate', function (selected) {
        if (typeof selected.date !== 'undefined') {
            var minDate = new Date(selected.date.valueOf());
            $('.end_date').datepicker('setStartDate', minDate);
        }
    });
                
$('.end_date')
    .datepicker({format: "yyyy-mm-dd"})
    .on('changeDate', function (selected) {
        if (typeof selected.date !== 'undefined') {
            var maxDate = new Date(selected.date.valueOf());
            $('.start_date').datepicker('setEndDate', maxDate);
        }
    });

var minDate = new Date('2019-07-30');
$('.start_date').datepicker('setStartDate', minDate);
$('.start_date').datepicker('setDate', minDate);

var maxDate = new Date('2019-08-04');
$('.end_date').datepicker('setEndDate', maxDate);
$('.end_date').datepicker('setDate', maxDate);
```

My `start_date` doing well when I set the date as it's startDate/minDate. But my `end_date` don't want to display the date when I set it as endDate/maxDate.

I am using v 1.8.0.

@Azaret @vsn4ik

**Comment by Azaret** [comment]
Hi @conangithub, Looks like the picker take time into account, you should specify time like so: `var maxDate = new Date('2019-08-04 00:00:00');`

**Comment by conangithub** [comment]
I set it using format `'2019-08-04 00:00:00'`. It doesn't display any value and also I can't select any date.

**Comment by conangithub** [comment]
I close this issue. I am sorry. I already used other library.
