### ISSUE TITLE
forceParse doesn't obey yyyy year format

### ISSUE THREAD

**Issue by lcsqlpete** [uxsolutions/bootstrap-datepicker#2509]
### Expected behaviour
With the date format set to mm/dd/yyyy, if I enter a date such as 3/1/19, it should be reformatted as 03/01/2019

### Actual behaviour
The date is formatted as 03/01/19 (month and day correct, 2-digit year instead of 4) 

### Datepicker version used
1.9.0
ex. 1.6.1.

**Comment by Azaret** [comment]
Hi, 

This is the expected behaviour since the year 19 is correct and match the format.
If you want `19` to be assumed as the year `2019` then set the option [`assumeNearbyYear`](https://bootstrap-datepicker.readthedocs.io/en/latest/options.html#assumenearbyyear) to `true`.
