### ISSUE TITLE
Date range selection only works when going backwards?

### ISSUE THREAD

**Issue by GeeZuZz** [uxsolutions/bootstrap-datepicker#2512]
### Actual behaviour
When I click a date, and then click a date later then the one I first selected, it just sets both dates to the one I selected. It does not show any range either.

However, if I click a date, and then select a previous date, it does seem to work.

### Expected behaviour
- Click "FROM" input to show calendar
- Click a date
- Active input field switches to "TO" input (but calendar still showing, just changes arrow to which it points to).
- All dates in range is highlighted while hovering
- When second date is clicked, calendar closes.

Can be reproduced here: https://uxsolutions.github.io/bootstrap-datepicker/ (select range, choose a date, then click a future date)

**Comment by Azaret** [comment]
Hi, I'm not sure to understand how to raise thise issue, I reproduced the steps and it works as expected. Could you make a video of it maybe?

**Comment by GeeZuZz** [comment]
> Hi, I'm not sure to understand how to raise thise issue, I reproduced the steps and it works as expected. Could you make a video of it maybe?

I made a video: https://gfycat.com/definitethankfulhen

After I click 1, I expect the other dates to be highlighted as I move my mouse to the right towards 5. And when I click on 5, I expect the end date input text to be set to the one I clicked last.

**Comment by Azaret** [comment]
I see, well that's not how the DateRange component works. the first datepicker sets the start date and the second one sets the end date. In case you select a end date lower than a start date or the other way around it happens that both datepicker will update the other date to avoid a negative period, but that's it, you can't set both start date and end date with one datepicker natively.
