### ISSUE TITLE
integration with ASP.NET Core MVC not working

### ISSUE THREAD

**Issue by PrithiviRathinam** [uxsolutions/bootstrap-datepicker#2546]
### Actual behaviour
I am using DatePicker in a input control that is binding to model using asp-for tag helper but that date after selecting, often times not going to the POST result in the code after I press submit button

### Datepicker version used

1.9.0.

### Example code

Jsfiddle example to reproduce the problem.

**Comment by PrithiviRathinam** [comment]
I am able to solve the problem by changing the format option.

**Comment by mcrosales-itfaq** [comment]
How did you able to solve your issue? I am facing with the format option now. Here is the link: https://github.com/uxsolutions/bootstrap-datepicker/issues/2648
