### ISSUE TITLE
Date range not selected in calendar after value changed programmatically

### ISSUE THREAD

**Issue by len-ny** [uxsolutions/bootstrap-datepicker#2573]
### Example code

```
	<div class="input-group input-daterange">
		<input type="text" id="startDate"
			class="form-control" name="startDate" value="2020-08-01"> 
		<span class="input-group-addon">to</span> 
		<input type="text" id="endDate" 
			class="form-control" name="endDate" value="2020-08-08">
	</div> 

    <script>
    $(document).ready(function() {
	    $('.input-daterange').datepicker( { 
	    	format: 'yyyy-mm-dd',
	    	autoclose: true
		});  	    
    	   
	    //change date
	    $('#startDate').val('2022-01-19');  
	    $('#endDate').val('2022-01-29');      
	    
		var startDate = new Date($('#startDate').val());
		var endDate = new Date($('#endDate').val());
	
		var $start = $(".input-daterange").find('#startDate');
		var $end = $(".input-daterange").find('#endDate')	
		$start.datepicker('setStartDate', startDate);
		$end.datepicker('setEndDate', endDate);
    });	 	
    </script>
```

### Expected behaviour
![image](https://user-images.githubusercontent.com/43208828/85200589-5177e900-b32b-11ea-84ef-f2207bf340e0.png)

### Actual behaviour
![image](https://user-images.githubusercontent.com/43208828/85200507-89326100-b32a-11ea-9809-a2b937a05b5e.png)

### Datepicker version used

datepicker : v1.9.0
bootstrap: v3.4.1
jquery: v3.4.1

**Comment by Eraness88** [comment]
Thank you very much for your help. It is very useful.

**Comment by darkarchon** [comment]
It's working as expected.
You can see it on screenshot I've bordered results of your code (inactive dates has a little bit lighter color).
Your code is set **date limits** on the calendar, by using `setStartDate` and `setEndDate` methods (other dates now can't be selected).
You spend so much time to wrote details and find solutions, next time try to find official docs of methods

Thank you for your detailed explanations to reproduce the occasion.

![datepicker_range](https://user-images.githubusercontent.com/469352/102715766-4274f200-42e0-11eb-8c59-e30d286c38ea.png)
