### ISSUE TITLE
language option doesn't work and positioning is problematic

### ISSUE THREAD

**Issue by RayL2590** [uxsolutions/bootstrap-datepicker#2611]
### Expected behaviour
Display the calendar in a specific language
Display the calendar in top or in bottom of the input

### Actual behaviour
Display the calendar in English
Display the calendar over the input and far in the bottom or in the top if I use the option orientation: "top auto"

### Datepicker version used

ex. 1.9.0.

### Example code
```
<form action="search.php" class="form-inline" method="POST" autocomplete="off">
      <input class="form-control" type="search" aria-label="Search" name="search" id="datepicker">
      <button type="submit" name="submit-search" class="btn btn-light">Search</button>
</form>

<script>
        $(document).ready(function(){
            $('#datepicker').datepicker({
                language: "fr",
                format: 'yyyy-mm-dd',
               orientation: "top auto"
                })
              })
  </script>
```

I tried several versions of Jquery, bootstrap, bootstrap-datepicker and I have always the same problems : the language doesn't change and the calendar is not positioning well.

**Comment by joeltnlsn** [comment]
We had the same language issue.
Try to include the specific locale-File.  (dist/locales)
`<script src="/static/scripts/bootstrap-datepicker.min.js"></script>`
`<script src="/static/locales/bootstrap-datepicker.de.min.js"></script>`

**Comment by RayL2590** [comment]
Thanks it works ;)

**Comment by toxpal** [comment]
Did you get position to work? I have the same issue with auto positioning.
