### ISSUE TITLE
Can we get a release?

### ISSUE THREAD

**Issue by rkt739** [uxsolutions/bootstrap-datepicker#2679]
My jQuery Migrate keeps complaining that there are deprecated jQuery functions in the package. I'd rather not have to fork, but it will keep complaining either until I do or until a fixed version of bootstrap-datepicker comes out.

The fix in question has already been [made and merged into the master branch.](https://github.com/uxsolutions/bootstrap-datepicker/pull/2579) Can't it go into a release sometime soon?

**Comment by acrobat** [comment]
Hi @rkt739, I will look into creating a bugfix release in the next few days!

**Comment by acrobat** [comment]
@rkt739 [`1.10.0`](https://github.com/uxsolutions/bootstrap-datepicker/releases/tag/v1.10.0) is released!

**Comment by diesl** [comment]
@acrobat Could you please add some release information in CHANGELOG.md? Thanks!
