### ISSUE TITLE
how to disable tooltip in range date option

### ISSUE THREAD

**Issue by VladTech-dev** [uxsolutions/bootstrap-datepicker#2684]
Hey guys, how do you disable these tooltips that pop up only during date-range option. See the attached.

to reproduce here -> https://uxsolutions.github.io/bootstrap-datepicker/?markup=range&format=&weekStart=&startDate=&endDate=&startView=0&minViewMode=0&maxViewMode=4&todayBtn=false&clearBtn=false&language=en&orientation=auto&multidate=&multidateSeparator=&keyboardNavigation=on&forceParse=on#sandbox
select range and click on the date input field to see, same date. 

![PXL_20230712_182726506](https://github.com/uxsolutions/bootstrap-datepicker/assets/63524658/4a3efa5f-c8dc-4a82-a356-158352b23893)

**Comment by macomuzul** [comment]
That may be a problem with your input. I am using v1.9 and I didn't get those popups and I tried with chrome, edge and firefox.
What version are you trying? These are the ones I'm using
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" />
  <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
![bootstrapdatepicker](https://github.com/uxsolutions/bootstrap-datepicker/assets/117616130/43d52504-cf47-42ba-8b84-3600a1a67264)

**Comment by macomuzul** [comment]
Ooops didn't send the image correctly
https://github.com/uxsolutions/bootstrap-datepicker/assets/117616130/43d52504-cf47-42ba-8b84-3600a1a67264

**Comment by macomuzul** [comment]
Also tried with the page you provided and still nothing. What browser are you using?

**Comment by VladTech-dev** [comment]
> Also tried with the page you provided and still nothing. What browser are you using?

Hey, im using latest version "Datepicker for Bootstrap v1.9.0 (https://github.com/uxsolutions/bootstrap-datepicker)".

I tried in chrome, brave, firefox. To me it seems browser auto complete is doing something funny. If i use the demo page provided by the datepicker, i get the same issue.

**Comment by VladTech-dev** [comment]
just fixed it, add -> autocomplete="off" to form tag.

**Comment by macomuzul** [comment]
Glad you solved it bro

**Comment by VladTech-dev** [comment]
> Glad you solved it bro

Thank you for your help :)
