### ISSUE TITLE
disable year having only 2 digits

### ISSUE THREAD

**Issue by marijusGood** [uxsolutions/bootstrap-datepicker#2701]
### Expected behaviour
hi team, entaring the date manually 12/12/24 is valid and we would like to allow only 12/12/2024. how would one do that? Thanks!

### Datepicker version used

ex. 1.9.0.

**Comment by ralfhauser** [comment]
Even better would be to automatically convert the two-digit year to four digits and have both entry-formats be acceptable in parallel

**Comment by marijusGood** [comment]
`assumeNearbyYear: true` is needed, no new feature is needed
