### ISSUE TITLE
$.datepicker.setDefaults() available?

### ISSUE THREAD

**Issue by tdm00** [uxsolutions/bootstrap-datepicker#288]
I looked all over for this but I don't see a way to set default options for all datepickers like I can with jQuery-UI. Is such an option available in the present version?

Thanks for this very helpful version of the datepicker!

**Comment by mikechamberlain** [comment]
As this was the top hit on Google for me when I searched, the latest version of the datepicker requires something like this:

```javascript
$.extend($.fn.datepicker.defaults, {
    autoclose: true,
    format:'d M yyyy',
    orientation:'bottom left',
    todayHighlight: true,
    showOnFocus: false
});
```
