### ISSUE TITLE
Clicking a number for the next month in December goes backwards

### ISSUE THREAD

**Issue by nfrancis** [uxsolutions/bootstrap-datepicker#302]
When looking at the calendar for December, 2012 and pressing the number 4 for the next month (Jan 4, 2013), it instead selects November 4, 2012. 

Screenshot:
![Screen 20Shot 202013-01-04 20at 204 00 16 20PM](https://f.cloud.github.com/assets/1709900/45378/1d04d030-577a-11e2-95d9-2248cdcfe2f0.png)

Click the 4 and it selects November 4 instead of what should be January 4.

**Comment by georgey58** [comment]
Do you know what fixed this. I cannot update to the latest master, so need to patch our version.
