### ISSUE TITLE
Disable (grey out) past dates or future dates in datepicker?

### ISSUE THREAD

**Issue by houmie** [uxsolutions/bootstrap-datepicker#329]
Is it possible to grey out all future days in the date picker? So that the user can only select today or any previous dates?

And also vice versa, where the user can only select future dates and cannot select any dates in the past?

These two features would be very handy.

**Comment by Niranth** [comment]
Answer solved on Issue-438. (Y)

**Comment by mohan1899** [comment]
Best Solution for disable future date...
var date=new Date();
      $('#datetimepicker').datetimepicker({
        format: 'MM/dd/yyyy',
        language: 'en',
		startDate : new Date('2015-01-01'),
		 endDate :  date
      });

**Comment by jkbansiwal** [comment]
Try this, it is working in my case:

    $(function () {   
            $('#Datein').datetimepicker(
                {
                    daysOfWeekDisabled: [0],
                    format: 'MM/DD/YYYY',                    
                    ignoreReadonly: true,
                    maxDate: 'now'
                }
              );
        });
