### ISSUE TITLE
Body top-margin not taken into account

### ISSUE THREAD

**Issue by MaxEvron** [uxsolutions/bootstrap-datepicker#348]
Please note that adding some top margin to `body` makes the dropdown not be position to the expected place. Instead, the dropdown will be placed lower as much pixels as the top-margin of the margin. Example `.body{top-margin:40px;}` makes the dropdown to be displayed 40px lower than expected.

**Comment by njbmartin** [comment]
This is still occuring in 1.4.0. As @aozora suggested, try it with a bootstrap page using a fixed navbar.

**Comment by lode** [comment]
Except that the datepicker falls under the fixed navbar, see the discussion here https://github.com/eternicode/bootstrap-datepicker/issues/1317#issuecomment-120718972
