### ISSUE TITLE
Add option for formatting a date before submit

### ISSUE THREAD

**Issue by anthonator** [uxsolutions/bootstrap-datepicker#373]
It would be nice to be able to display the date in one format (mm/dd/yyyy) and send it to the server in a different format (yyyy-mm-dd).

**Comment by geri777** [comment]
My solution is to send the date as text as it is - and put the current date format into the hidden field. On the server side I calculate the date object based on both value. This has 2 advantages:
- if anything goes wrong with Javascript, I still can process the date. 
- I also get the date if the user does not change the date and submits as it is

**Comment by moisesh18** [comment]
@geri777 I didn't get it. Could you please explain it again?
When you said "the date as text as it is" you referred, for example, to "31/12/2020"?
And when you said "current date format" you referred to "dd/mm/yyyy"?
And with this case, in server side you use functions like "createFromFormat"?
Or what is the purpose of that?
