### ISSUE TITLE
startDate option disabling past dates with current date

### ISSUE THREAD

**Issue by itskawsar** [uxsolutions/bootstrap-datepicker#438]
I wanted to disable all past date before current date and using following code:

$('#date').datepicker({ 
    startDate: new Date() 
});

It works fine. But it is disabling date till today. As example if today is 04-20-2013 and i disable past dates by setting startDate: new Date(). but I can select date from 04-21-2013

**Comment by manishgumber** [comment]
Thank you.

**Comment by aspnaren** [comment]
You can use data attributes like data-date-startdate=’yyyy-mm-dd’ or use the startDate attribute while initializing the date picker. You can know more about disabling past dates in bootstrap datepicker here http://codezag.com/disabling-past-dates-bootsrap-datepicker/

**Comment by DeepzSandra** [comment]
Narendran Parivallal  It's not working properly

**Comment by chaitu111** [comment]
<script type="text/javascript">
$('.datepicker').datepicker({
    format: 'dd/mm/yyyy',
    todayHighlight:'TRUE',
	startDate: '-0d',
	autoclose: true,
})

**Comment by mizanur-rahman** [comment]
Awesome!!! Thanks Bro!!

`//disabling past date from datepicker`
`var nowDate = new Date();`
`var today = new Date(nowDate.getFullYear(), nowDate.getMonth(), nowDate.getDate(), 0, 0, 0, 0);`
`//initializing datepicker`
`$('.datepicker').datepicker({format:'yyyy-mm-dd', startDate: today });`

@saschaglo
Great work :+1:  Thanks again :)

**Comment by jMahapatra** [comment]
It's worked for me..!! Thanks..
startDate: new Date();

**Comment by priyanka-Sadh** [comment]
@saschaglo

Thanks ! 
Your code helps me :)

**Comment by Nurhaifaa** [comment]
Hi, can I know whether how to do if I'm using typescript language?

**Comment by soumenpandit** [comment]
var dateToday = new Date();
			var dates = $("#from, #to").datepicker({
				defaultDate: "+1w",
				changeMonth: true,
				numberOfMonths: 3,
				autoclose: true,
				minDate: dateToday,
				onSelect: function(selectedDate) {
					console.log('ddrgdfgfd')
					var option = this.id == "from" ? "minDate" : "maxDate",
						instance = $(this).data("datepicker"),
						date = $.datepicker.parseDate(instance.settings.dateFormat || 



$.datepicker._defaults.dateFormat, selectedDate, instance.settings);
					dates.not(this).datepicker("option", option, date);
				}
			});
write this code but "to" date disable date not working
