### ISSUE TITLE
changeMonth event is not triggering

### ISSUE THREAD

**Issue by geetmenon** [uxsolutions/bootstrap-datepicker#471]
Is changeMonth event not supported? I added the following "changeMonth" event handler. But it is not getting triggered when I click on the arrows to move to next or previous month. If I change the event type to "changeDate", it gets triggered when I click on a date and the alert gets displayed.

$("#claimDate").datepicker().on('changeMonth', function (ev) {
                        alert("changed");
                        });

**Comment by rogersbrad** [comment]
changeMonth: true   has no effect, does not show nor trigger?    noticed others with the problem from similar posts from back in 2013, has this been resolved?

**Comment by HartLarsson** [comment]
there are also some undocumented triggers:

changeHour
changeMinute


should be great to trigger when during time picking after selecting Hour will apear the minutes to pick to process some view tweak like:

```
   $(".table-condensed .prev").css('visibility', 'hidden');
    $(".table-condensed .switch").text("Pick Time");
    $(".table-condensed .next").css('visibility', 'hidden');
```
but seems it trigger asap you select a hour or a miute and cannto be used to "know" in witch view the user is (hour pick or minute pick)
