### ISSUE TITLE
Input field disappears after selecting a date

### ISSUE THREAD

**Issue by frizbee** [uxsolutions/bootstrap-datepicker#478]
![datapicker](https://f.cloud.github.com/assets/645636/576668/177e4d08-c80e-11e2-91df-4dc6453153f0.jpg)

Can't find solution
Use with joomla 3.1 + Bootstrap

Is anyone had anything similar, please help.

**Comment by SerenadeX** [comment]
I'm dealing with this problem right now, mainly cause I am working on a magento app which uses prototype.js.  Can't help that one.  It would be nice if it didn't hide the element.  I hate to have to use a hacky solution to make this awesome tool work.

**Comment by jonerd** [comment]
I had the same issue. Just rename this._trigger('hide') to this._trigger('hideDatepicker') to prevent the input field from disappearing. Accordingly you can then listen for 'hideDatepicker' event instead for 'hide' event.

**Comment by gowrizrh** [comment]
using jQuery 3.3.x with proto 1.7, input field disappears after clicking datepicker/timepicker.
