### ISSUE TITLE
Language data option not working

### ISSUE THREAD

**Issue by Nerian** [uxsolutions/bootstrap-datepicker#48]
Hi,

I have the following code:

```
<input class="data-datepicker" data-date="2012-04-20" id="task_last_day_to_submit" language="es" name="task[last_day_to_submit]" type="text" value="2012-04-20" />
```

```
$(document).ready(function() {
    $(document).on("focus", ".data-datepicker", function(e){
        $(this).datepicker({"format": "yyyy-mm-dd", "weekStart": 1, "autoclose": true});
      });
});
```

But the display is shown in english.

Passing the option as an argumento do work as expected.

```
$('.data-datepicker').datepicker({"format": "yyyy-mm-dd", "weekStart": 1, "autoclose": true, "language":"es"});
```

**Comment by arturmamedov** [comment]
why don't add it to the documentation that we can use data-date-language .. i spent an hour for find this issue, thank you a lot for grat plugin and work

**Comment by arg3ni5** [comment]
for example: you need use spanish(es):
First you, need add the file in locales\bootstrap-datepicker.es.min.js and then use the data option: ` data-date-language="es"`
