### ISSUE TITLE
Datepicker inside a modal window causes modal to close

### ISSUE THREAD

**Issue by scottharvey** [uxsolutions/bootstrap-datepicker#50]
I've got a couple of datepicker input fields inside a form that is displayed within a Bootstrap modal window. When I select a date using the datepicker the modal window closes.

This is happening due to the trigger that gets executed on line 146:

https://github.com/eternicode/bootstrap-datepicker/blob/fd9eb6bb7e9a9785f960b3ff98aac105df5e3d32/js/bootstrap-datepicker.js#L146

When I comment out that trigger the datepicker still works fine.

Any thoughts as to what that trigger is for and how to make it work nice inside a modal window?

Scott

**Comment by Kingroys** [comment]
I know the post is a bit old but if it can helps, here's what I've done to fix it : 

//DATE PICKER
	$('.datepicker').datepicker().on('changeDate', function(ev) {
		//
	}).on('hide', function(event) {
		event.preventDefault();
		event.stopPropagation();
	});

**Comment by othyn** [comment]
@Kingroys Thank you! That solved my problem.

**Comment by kushalseth** [comment]
T
Thanks, It resolved my problem

**Comment by mdaynul** [comment]
@Kingroys  .. thanks, it works fine. This soultion really makes sense.

**Comment by danielwermann** [comment]
@Kingroys Thank you.

**Comment by fabi0w** [comment]
@Kingroys Thank you! That solved my problem in 2017!!.. 

```
$('.date2').datepicker('show')
$('.date2').datepicker('hide');
```
this code calling modal bootstrap hide!!

**Comment by nynhex** [comment]
I was fighting with this big time with a modal and bootstrap datepicker clearing my input fields.  Thanks to a friend who pointed me to this issue it solved my problem.

**Comment by keithmclaughlin** [comment]
@Kingroys Thanks man. That helped me out!

**Comment by vpatidarperficient** [comment]
Thanks @Kingroys Its worked for me !!!!

**Comment by mateusmx** [comment]
This still working on 2019 @Kingroys thanks a lot bro.

**Comment by Kingroys** [comment]
@mateusmx Glad if I can help :)

**Comment by sanjeevkse** [comment]
> I know the post is a bit old but if it can helps, here's what I've done to fix it :
> 
> ```js
> $('.datepicker').datepicker().on('changeDate', function(ev) {
> 	// YOUR CODE
> }).on('hide', function(event) {
> 	event.preventDefault();
> 	event.stopPropagation();
> });
> ```

Thank you so much. That solved my a day problem.

**Comment by chandanahuja193** [comment]
sanjeevkse would that work for antd design picker because i have  same problem in my model

**Comment by Kingroys** [comment]
You should try but I guess it'll work

**Comment by chandanahuja193** [comment]
Kingroys I am working in react and i am new in react so i donot know how to impleement it .
this is my Datepicker compoenet 
 <DatePicker
              className="inputcomponent_input"
              onChange={(e,a,b)=>this.handleDatePicker(e,a,b,item.name)} />

This is  handleDatePicker Method

handleDatePicker = (e,date,dateString,name) =>{
    //  console.log('handlePicker',e,date,dateString,name)
    const event =  window.event;
    //console.log('handlePicker',event.view.onfocus)
  
    

    this.setState({
      data:{
        ...this.state.data,
        [name]:dateString
      }
    },
    () =>{
    //  console.log('handlePicker', this.state)
    }
    )
  }

every time when clicks on it it closes the my reactstrap model.

**Comment by Kingroys** [comment]
This fix was made for jQuery. Not sure it's gonna work in your specific case. :(

**Comment by regis-bird** [comment]
> I know the post is a bit old but if it can helps, here's what I've done to fix it :
> 
> $('.datepicker').datepicker().on('changeDate', function(ev) {
> 	// YOUR CODE
> }).on('hide', function(event) {
> 	event.preventDefault();
> 	event.stopPropagation();
> });

2025 and this fix helps me, many thanks.

**Comment by Kingroys** [comment]
Glad it still helps after 10 years :)
