### ISSUE TITLE
AutoClose not working

### ISSUE THREAD

**Issue by leandrozapata** [uxsolutions/bootstrap-datepicker#500]
Hi, i use the autoclose method but this not working in Chrome:
js:

``` javascript
        $(document).ready(function () {                                  
            $('.datepicker').datepicker({
                format: "dd/mm/yyyy",
                autoclose: true
            });

        });        
```

html:

``` html
<input class="datepicker valid" data-val="true" data-val-date="El campo Vencimiento debe ser una fecha." id="FirstMaturiy" name="FirstMaturiy" readonly="readonly" type="text" value="">
```

Thanks for your help.

**Comment by clintgh** [comment]
I don't think this is compatible to touch events.
Mine is not working and is related to a plugin called "Touche.js" which converts click event to touch.
When I comment out the touche.js then it worked fine

**Comment by leomedeiros** [comment]
Changing the class name, as suggested by FlanTech solved the problem of autoclose for me.

**Comment by cezco** [comment]
i have a solved for this case,
download Datepicker for Bootstrap v1.4.0 (https://github.com/eternicode/bootstrap-datepicker)

Modify in your .js files :
- Change the bootstrap-datepicker.js (changed all autoclose, set it to true)
var defaults = $.fn.datepicker.defaults = { autoclose: true, todayBtn: true,....

- bootstrap-datepicker.min.js (changed autoclose, set it to 1)
var n=a.fn.datepicker.defaults={autoclose:1,beforeShowDay:a.noop,beforeShowMonth:a.noop,.....

put this in your code project:
- if you are using "bootstrap-datepicker.js" :
var datepicker = $.fn.datepicker.noConflict();
$.fn.datepicker.defaults.format = "dd/M/yyyy";
$.fn.bootstrapDP = datepicker;
$('.datepicker').datepicker({ autoclose: true, todayHighlight: true });

- if you are using "bootstrap-datepicker.min.js" :
var datepicker = $.fn.datepicker.noConflict();
$.fn.datepicker.defaults.format = "dd/M/yyyy";
$.fn.bootstrapDP = datepicker;
$('.datepicker').datepicker({ autoclose: 1, todayHighlight: 1 });


this for the input type :
<div class='input-group date' id='datepicker'>
<input class="form-control" type="text" name='startDate' data-provide="datepicker" data-date-format="mm/dd/yyyy" placeholder="Default input" >
<span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
</div>

i hope this is can help you

regards,
Herry

**Comment by acrobat** [comment]
@cezco can you provide a jsfiddle to show what the problem exactly is? (you can use [this jsfiddle](http://jsfiddle.net/vh1oknf7/) as a start)

**Comment by xedemx** [comment]
@acrobat 

Maybe the problem is how the markup is being set up? updated [your jsfiddle here](http://jsfiddle.net/vh1oknf7/118/) in a lame way (I am new to this), but the first example uses data-provide on the div, while the second is with an id on the input.

**Comment by m4gnetar** [comment]
I added the following line 

> this.hide();

 at the end of the "click" function (line 254 of boostrap-datepicker.js file) and it has worked:                        `case 'td':
						{...
                                                 ....
                                                     this.hide(); 
						}
						break;
`

**Comment by jduelferOmega** [comment]
mine worked by overriding the default for all datepickers:

`$.fn.datepicker.defaults.autoclose = true;`

But I didn't need it different for each individual datepicker, I wanted them all to autoclose.

**Comment by podisto** [comment]
Edit the file bootstrap-datepicker.js and add change directly this line of code 
```javascript
autoclose: true, // default false
```

**Comment by pienisieni** [comment]
autoclose stops working if jquery library is loaded twice -- at least that was the problem for me.

**Comment by TomaszWaszczyk** [comment]
How to solve the issue in case having AngularJS 1.2 application?

`                    <datetimepicker class="datepickerx" data-ng-model="events.filter.state.dateFrom"
                                    data-datetimepicker-config="{ minView: 'day' }" data-date-autoclose="true"
                    />`

Does not work ;/

**Comment by dimsis** [comment]
I've solved it by **removing the  data-provide="datepicker" from the outter div**.
After that autoclose worked and even the todayHighlight:true start working too.

**Comment by ulissesas** [comment]
For me it worked by changing the autoClose property to autoHide
I'm using version https://cdnjs.com/libraries/datepicker/1.0.10
