### ISSUE TITLE
Clear button, non-field element

### ISSUE THREAD

**Issue by mgray88** [uxsolutions/bootstrap-datepicker#523]
The clear button does not currently work with a non-field element. There is no discernible way to tell that the clear button was clicked.  I expected one of two things to occur:
1. The `data-date` attribute on the element datepicker is attached to should be cleared.
   OR
2. The event passed back in `changeDate` should have null date and timestamp properties.

I will try and fix these and submit a pull request, as I need this functionality.

edit: This does not appear to be a straightforward fix, so before I mutilate the source code trying, if you could take a look @eternicode that would be great. thanks!

**Comment by jabbett** [comment]
@eternicode Yes, the datepicker doesn't set `data-date`, but `update()` looks in that attribute to distinguish whether a value has been set/unset. If `clearDates` doesn't clear the attribute, `update()` will never do anything (including trigger `changeDate` or `clearDate`).
