### ISSUE TITLE
Help on how to use localization

### ISSUE THREAD

**Issue by murparreira** [uxsolutions/bootstrap-datepicker#532]
Call me stupid but i couldn't use the locale here.  
Copied the locale from `js/locale`, and pasted it after jQuery and Bootstrap-Datepicker being loaded. **No use**.  

I keep getting the same error, `Cannot set property 'en' of undefined`.  

On the original `datepicker` plugin, you just created a file, outside the document.ready scope, and used the setDefaults and locales methods.

**Comment by andreasalvi** [comment]
had the same problem. try to update bootstrap-datepicker.js
