### ISSUE TITLE
What is the proper way to set datepicker orientation?

### ISSUE THREAD

**Issue by first-developer** [uxsolutions/bootstrap-datepicker#561]
Hi I tried to use the 'orientation' option of the datepicker but it doesn't seem to work.

```
$(".datepicker").datepicker({
  orientation: "right bottom"
});
```

Thanks in advance

**Comment by kshipp** [comment]
Yes, it's backwards!  "Bottom" really means "top".  Please, please fix this.

**Comment by Nikola-K** [comment]
Just stumbled upon this after trying to figure out what's wrong, I agree that it makes more sense for "top" to show the picker, well, on top of the element and not on the bottom.

At the very least the docs should show an example with both code and pictures examples on how to properly use the orientation.

**Comment by tineyi** [comment]
Was this ever fixed?

**Comment by snaits** [comment]
@tineyi  it has a duplicate, which is fixed: https://github.com/eternicode/bootstrap-datepicker/issues/1406

**Comment by vinodv3** [comment]
it's working ......
	$(document).ready(function(){
	var date_input=$('input[name="date"]'); //our date input has the name "date"
	var container=$('.bootstrap-iso form').length>0 ? $('.bootstrap-iso form').parent() : "body";
		date_input.datepicker({
			format: 'mm/dd/yyyy',
			container: container,
			todayHighlight: true,
			autoclose: true,
			orientation: "left top",
		})
	})
