### ISSUE TITLE
Inline date range

### ISSUE THREAD

**Issue by jestinbrooks** [uxsolutions/bootstrap-datepicker#580]
Is it currently possible to do date ranges with an inline datepicker?  An example or 2 of the range datepicker on the demo page would be really nice too.

**Comment by janat08** [comment]
Isn't working I think.

**Comment by danielleford04** [comment]
This is not working for me

**Comment by Raferner** [comment]
It's working for me, now I'll make the arrengements for the configurations I need, but it has been very usefull, thanks a lot for the appointment!
PD: I find it strange, but not all the properties work inline, as in an single-datepicker implementation; in my case, for example, data-date-format="dd/mm/yyyy" data-date-week-start="1" data-date-start-date="+1d" are working inline, but maxViewMode or languege have to be on the .datepicker( options_datepicker ) declaration.
