### ISSUE TITLE
the displayed selected date is changed to today's date when call of update() is triggered

### ISSUE THREAD

**Issue by leisti** [uxsolutions/bootstrap-datepicker#593]
I have two date input fields on a page, for inputting a date range.  My problem is that when I update the beginning-of-range date, the Javascript function I've written to update the end-of-range input does successfully change the date-as-text that is displayed to the user, and the hidden date-in-ISO-format field that is read when the user submits the form, but when the user opens the end-of-range datepicker, the selected date (highlighted with the blue box) has now become today's date.

I have a web application built using Ruby on Rails and Bootstrap.  For input, I'm using the Rails SimpleForm gem, which generates the following HTML:

```
<div class="control-group my_datepicker optional
     filtering_criteria_the_start_date">
  <label class="my_datepicker optional control-label"
         for="filtering_criteria_the_start_date">Date range (from)</label>
  <div class="controls">
    <div class="input-append">
      <input class="my_datepicker optional my_datepicker"
             data-date-format="yyyy-mm-dd"
             id="filtering_criteria_the_start_date"
             name="filtering_criteria[the_start_date]" readonly="readonly"
             type="text" value="09 Aug 2013" />
      <input class="my_datepicker optional" id="the_start_date_hidden"
             name="filtering_criteria[the_start_date]" type="hidden"
             value="09 Aug 2013" />
      <span class="add-on" id="the_start_date_datepicker_icon">
        <i class="icon-calendar"></i>
      </span>
    </div>
  </div>
</div>
<div class="control-group my_datepicker optional
            filtering_criteria_the_end_date">
  <label class="my_datepicker optional control-label"
         for="filtering_criteria_the_end_date">Date range (to)</label>
  <div class="controls">
    <div class="input-append">
      <input class="my_datepicker optional my_datepicker"
             data-date-format="yyyy-mm-dd"
             id="filtering_criteria_the_end_date"
             name="filtering_criteria[the_end_date]" readonly="readonly"
             type="text" value="09 Aug 2013" />
      <input class="my_datepicker optional" id="the_end_date_hidden"
             name="filtering_criteria[the_end_date]" type="hidden"
             value="09 Aug 2013" />
      <span class="add-on" id="the_end_date_datepicker_icon">
        <i class="icon-calendar"></i>
      </span>
    </div>
  </div>
</div>
```

Here's the jQuery script I'm using with the HTML:

``` javascript
    $(document).ready(function() {

      var today = new Date();
      var today_in_display_format = dateFormat(today, "myDateFormat");

      /* Convert the icon component of the start-of-range date input field to a
         datepicker. */
      $('#the_start_date_datepicker_icon')
        .datepicker({
          format     : 'dd M yyyy',
          autoclose  : true,
          startDate  : '01 Jan 2000',
          endDate    : today_in_display_format,
          todayBtn   : 'linked',
          autoclose  : true
        }).on('changeDate', function(the_date) {
          /* When the user selects a new date, update the form's hidden input
             field, containing the ISO 8601-format date, to match the selected
             date. */
          var start_date_in_display_format = the_date.format('dd M yyyy');
          var start_date_in_iso_format = dateFormat(start_date_in_display_format,
                                                    "isoDate");
          $(this).parent().find('#filtering_criteria_the_start_date').val(start_date_in_display_format);
          $(this).parent().find('#the_start_date_hidden').val(start_date_in_iso_format);
          /* Update the end-date datepicker so that its startDate is the same as
             the date the user just selected for the start date. */
          update_end_of_range_datepicker(start_date_in_display_format,
                                         start_date_in_iso_format);
        });

      /* Convert the icon component of the end-of-range date input field to a
         datepicker. */
      $('#the_end_date_datepicker_icon')
        .datepicker({
          format     : 'dd M yyyy',
          autoclose  : true,
          startDate  : today_in_display_format,
          endDate    : today_in_display_format,
          todayBtn   : 'linked',
          autoclose  : true
        }).on('changeDate', function(the_date) {
          /* When the user selects a new date, update the form's hidden input
             field, containing the ISO 8601-format date, to match the selected
             date. */
          var end_date_in_display_format = the_date.format('dd M yyyy');
          var end_date_in_iso_format = dateFormat(end_date_in_display_format,
                                                  "isoDate");
          $(this).parent().find('#filtering_criteria_the_end_date').val(end_date_in_display_format);
          $(this).parent().find('#the_end_date_hidden').val(end_date_in_iso_format);
        });

      /* Set (a) the start-of-range and (b) the chosen date of the end-date datepicker to the values
         given as parameters.  Here, the abbreviation "nsdfed" means "new start date for end date". */
      function update_end_of_range_datepicker(nsdfed_in_display_format,
               nsdfed_in_iso_format) {
        $('#the_end_date_datepicker_icon').datepicker('setStartDate',
                                                      nsdfed_in_display_format);
        var end_date_in_iso_format = $('#the_end_date_hidden').attr('value');
        if (nsdfed_in_iso_format > end_date_in_iso_format) {
          /* If the selected end date is now earlier than the new start date,
             advance the former to equal the latter. */
          end_date_in_iso_format = nsdfed_in_iso_format;
          var end_date_in_display_format = dateFormat(end_date_in_iso_format,
                                                      "myDateFormat");
          var end_date = new Date(end_date_in_display_format);
          $('#the_end_date_datepicker_icon').datepicker('setDate', end_date);
          $('#the_end_date_datepicker_icon').datepicker('update');
          $('#filtering_criteria_the_end_date').val(end_date_in_display_format);
          $('#the_end_date_hidden').val(end_date_in_iso_format);
        }
      }

      /* Initialize the hidden input fields when the page is loaded, so that the "Search" button can be
         used immediately. */
      var start_date_in_display_format = $('#filtering_criteria_the_start_date').attr('value');
      var start_date_in_iso_format = dateFormat(start_date_in_display_format, "isoDate");
      $('#the_start_date_hidden').val(start_date_in_iso_format);
      var end_date_in_display_format = $('#filtering_criteria_the_end_date').attr('value');
      var end_date_in_iso_format = dateFormat(end_date_in_display_format, "isoDate");
      $('#the_end_date_hidden').val(end_date_in_iso_format);
    })
```

myDateFormat is a format I've added to date.format.js, to match the format produced by the datepicker's 'dd M yyyy' format definition:

``` javascript
    dateFormat.masks = {
        "default":      "ddd mmm dd yyyy HH:MM:ss",
        myDateFormat:   "dd mmm yyyy",
    ...
```

I'm hanging the datepickers on the calendar icons displayed immediately to the right of the read-only text field that shows the selected date, for esthetic reasons -- I don't want the datepicker to appear when the text field itself is clicked.

No problem follows from changing either date from the datepickers themselves on the date thus directly changed, but when I change the start-of-range date, the very first line of function `update_end_of_range_datepicker` -- that is, the call of the end-of-range datepicker's `setStartDate` function -- causes the problem I described.

I've tested the foregoing by (1) loading the page, (2) selecting the date 01 Aug 2013 for start-of-range, (3) selecting date 07 Aug 2013 for the end-of-range, and (4) by selecting the date 04 Aug 2013 for start-of-range.  In steps (2) and (4), the `update_end_of_range_datepicker` function is called, and it calls `setStartDate` on the end-of-range datepicker.  In step (2), I have not yet changed the selected end-of-range from today (09 Aug 2013), because it's not yet possible, because the start date is also today. The calls of `setStartDate` in steps (2) and (4) do work in the sense that the dates available to the end-of-range datepicker are update correctly. However, after step (4), clicking on the end-of-range input field's calendar icon brings up a calendar where the blue box that indicates the selected date is not 07 anymore, but 09, as shown in this screenshot fragment:

![eternicode-datepicker-bugreport](https://f.cloud.github.com/assets/1375036/938289/696203f6-00fa-11e3-80fa-f1bbb120068c.png)

I'm using the latest version of the bootstrap-datepicker.js and bootstrap-datepicker.css files, downloaded today, and have added the two calls of `alert` to the former file:

```
...
setValue: function() {
    var formatted = this.getFormattedDate();
    alert('in setValue: formatted == ' + formatted);
    if (!this.isInput) {
...
setStartDate: function(startDate){
    alert('in setStartDate: startDate == ' + startDate);
    this._process_options({startDate: startDate});
...
```

In step (1), this produces two alerts. The first is **in setStartDate: startDate == 01 Jan 2000**, and the second **in setStartDate: startDate == 09 Aug 2013**. In step (2), two alerts are produced; the first one says **in setValue: formatted == 01 Aug 2013**, and the second one **in setStartDate: startDate == 01 Aug 2013**.  In step (3), one alert is produced, saying **in setValue: formatted == 07 Aug 2013**.  (And remember that after this step, the blue highlight square appears in the correct place for both datepickers when the calendar icons are clicked: on 01 and on 07 Aug.) And finally in step (4), two alerts are produced; the first one says **in setValue: formatted == 04 Aug 2013**, and the second one **in setStartDate: startDate == 04 Aug 2013**.

I experimented with changing (a) the initial value of the end-of-range date given in the datepickers' initializers, and (b) the initial value of the displayed date in the HTML code. In all cases, it is the former value that becomes the date which is highlighted in blue after step 4 -- the date values given in the HTML code do not have an effect on this behaviour.

Other debugging I've done seems to indicate that it's the `update` function of datepicker.js, called by the `setStartDate` function among others, that causes this bug. Or is it a bug; am I instead just doing something wrong?

**Comment by Markkos89** [comment]
hello.. im having a similar issue but my datepicker's date is changing to today's date when I submit the form... so trought a post/insert I'm saving all the data with today's date and it doesnt have to be this way...
