### ISSUE TITLE
Datepicker not working inside bootstrap modal

### ISSUE THREAD

**Issue by Youssef-Siblini** [uxsolutions/bootstrap-datepicker#600]
Hi,

The datepicker is working fine in all pages but when I add it inside a bootstrap modal (link below) it stop working.

Link to bootstrap modal documentation: http://getbootstrap.com/2.3.2/javascript.html#modals 

Many Thanks,

Joe

**Comment by etechpulse** [comment]
Go through the working cross browser bootstrap datepicker example in asp.net web applications. Refer to http://www.etechpulse.com/2015/11/bootstrap-datepicker-calendar-example.html

**Comment by Erandakuruneru** [comment]
<style>
  .datepicker{z-index:1151 !important;}
</style>
