### ISSUE TITLE
Keyboard navigation disabled by clicking the calendar

### ISSUE THREAD

**Issue by aljungberg** [uxsolutions/bootstrap-datepicker#617]
When a date input is clicked to bring up the datepicker, keyboard navigation is possible using the arrow keys. If a date is now clicked with the mouse, the input field loses keyboard focus and keyboard navigation is no longer possible.
## Steps to reproduce
- Run this fiddle: http://jsfiddle.net/aljungberg/tNdCf/1/
- Click the text field.
- Hit the right arrow key and see date change.
- Click some date.
- Hit the right arrow key.

Expected result:
date changes

Actual result:
nothing happens

I believe that the datepicker should react to clicks by doing whatever it wants to do and then refocusing the input field as to retain the ability to catch key up events.

**Comment by Manish2612** [comment]
I am still facing this issue in 1.7.1. using NPM repository to install dependency.
