### ISSUE TITLE
Date range is static in RoR

### ISSUE THREAD

**Issue by fchampreux** [uxsolutions/bootstrap-datepicker#657]
Hi, I can't get the behaviour of the date range (end > start etc.).

I opened a question with my code http://stackoverflow.com/questions/19346781/how-to-retrieve-a-range-from-bootstrap-datepicker-rails

Can you help me ?

Thanks.

Best regards,

Fred

**Comment by petrsigut** [comment]
I made the same mistake - I got it wrong from the docs?

https://bootstrap-datepicker.readthedocs.io/en/stable/markup.html#daterange

> Note that that input-daterange itself does not implement the datepicker methods. Methods should be directly called to the inputs. For example:
