### ISSUE TITLE
Setting the date to today

### ISSUE THREAD

**Issue by dittore** [uxsolutions/bootstrap-datepicker#7]
Hi,

How can I set the date to be today, e.q. 26-2-2012, when user opens datepicker?

I tried different ways but nothing updated the selected date on datepicker.

**Comment by santosh-k1** [comment]
Hi, i have used below code which is how one month before date not current date:
  $('.datepicker').datepicker(
  {
      format: 'dd/mm/yyyy',
      autoclose: true,
      forceParse: false,
      Default: true,
      pickDate: true,   
      todayHighlight: true,
      //initialDate: new Date('15/10/2016'),
  }).load('show', function (ev) {
      var today = new Date();
      var currentDate = today.getDate() + "/" + today.getMonth() + "/" + today.getFullYear();
      $(this).val(currentDate);
  });

**Comment by santosh-k1** [comment]
Hi,
Here is easy use of current date selected value in the textbox

$('#datepicker').datepicker(
today()
);
function today(){
	var d = new Date();
	var curr_date = d.getDate();
	var curr_month = d.getMonth() + 1;
	var curr_year = d.getFullYear();
  var currentDate = curr_date + "-" + curr_month + "-" + curr_year;
  $('#datepicker').val(currentDate);
}

**Comment by moinulmithu** [comment]
Solution of santosh-k1 worked nicely for me. Thanks a lot @santosh-k1

**Comment by santosh-k1** [comment]
welcome @moinulmithu :+1:
