### ISSUE TITLE
Bootstrap 3 doens't have icon-arrow-left and others anymore

### ISSUE THREAD

**Issue by renathy** [uxsolutions/bootstrap-datepicker#717]
Bootstrap-select doesn't show icons on Bootstrap 3.
It references icon-arrow-left, but it doesn't exists in Bootstrap 3.

**Comment by lcsqlpete** [comment]
I'm also not seeing the navigation arrows in Bootstrap 3.  I found the following code in my bootstrap-datepicker.js file:

`'<tr>'+
								'<th class="prev">&lsaquo;</th>'+
								'<th colspan="5" class="switch"></th>'+
								'<th class="next">&rsaquo;</th>'+
							'</tr>'+`

That looks like the html entity characters referred to above but no arrows are displayed.
