### ISSUE TITLE
Options dont work

### ISSUE THREAD

**Issue by caarlos0** [uxsolutions/bootstrap-datepicker#76]
I've doing some tests here... and seems like autoClose and weekStart dont work (trunk version).

**Comment by AnthonyBRoberts** [comment]
I know this is a closed issue, but I have a use case for needing to change options, or at least have two datepickers with unique options.  One requires format m/yyyy, and when flag is flipped, needs to show d/m/yyyy.  Slightly different functions on the changeDate event also.  Any chance it's possible to have two distinct datepickers on the same page?  It's for a backbone.js application, so the element is part of a view.  Most of what I found on StackOverflow and Google was unanswered questions.

This issue aside, I do like this widget. It's simple, but has the right options, if I can have two option sets. Thanks,

**Comment by acrobat** [comment]
Is this what you mean with 2 datepickers with seperate options? http://jsfiddle.net/zcvq0yhh/3/
