### ISSUE TITLE
disable toggle?

### ISSUE THREAD

**Issue by zh99998** [uxsolutions/bootstrap-datepicker#775]
i'm using bootstrap-datepicker and get into trouble.

when i click a day, it works well，but when i click the same day again. the select was canceled....

the online demo http://eternicode.github.io/bootstrap-datepicker/ works well. click again same day will keep the selection.......

i have read the docs and can't find anyway to disable toggle......

**Comment by altinselimi** [comment]
This is still broken in 1.6.4

**Comment by acrobat** [comment]
@altinselimi Can you create a new issue for this with an example on 1.6.4 to reproduce the problem? Thanks!
