### ISSUE TITLE
Datepicker not highlighting dates on Bootstrap modal

### ISSUE THREAD

**Issue by renierdbruyn** [uxsolutions/bootstrap-datepicker#782]
The date picker is not highlighting the selected dates on Bootstrap 3 model:
![modal-datepicker](https://f.cloud.github.com/assets/4373602/1910303/e0e21106-7d13-11e3-9343-8661915e8529.PNG)

This is my code:

``` javascript
$('#myModal').on('shown.bs.modal', function() {
            $("#dp3").datepicker({
                todayBtn : true,
                autoclose : true,
                todayHighlight : true,
                endDate: "current"
            });
```

Why is it not highlighting the date?

**Comment by abdulwahidgul24085** [comment]
You Sir are an actual legend. Thank you for helping me solve this problem.
