### ISSUE TITLE
Input disableTouchKeyboard

### ISSUE THREAD

**Issue by Glideh** [uxsolutions/bootstrap-datepicker#787]
In input mode, shouldn't we have a `disableTouchKeyboard` option to prevent mobile keyboard to pop out when the input is focused ?
Setting it `readonly` seems not a good idea for me as it suggests we can't change the value.

**Comment by MrSleeps** [comment]
I'm still having an issue with this, it still pops up the keyboard on both the Samsung s4 mini and Sony Xperia Z3 (android 4.4.2 and 4.4.4 respectively). Pulling my hair out on this one..

**Comment by gregblass** [comment]
This isn't working for me on an iPhone 6. I'm calling:

    $('.datepicker').datepicker({
      autoclose: true,
      disableTouchKeyboard: true
    });

But the keyboard is still coming up.

**Comment by CalamityJames** [comment]
Confirmed re-occuring on my Galaxy S6 Edge too running Android 5.0.2 on Chrome and stock browser.

Sorry chaps. Will try and find some time to dig back through the code and see what's different in newer rendering engines (maybe the `msMaxTouchPoints` or `ontouchstart` are not passed any more).

**Comment by razvanphp** [comment]
Can you try this? I don't have access to Android devices, but this code snippet is from a rather great library, [interact.js](https://github.com/taye/interact.js), so it should be actual.

````javascript
var supportsTouch = (('ontouchstart' in window) || window.DocumentTouch && document instanceof window.DocumentTouch);
````

**Comment by acrobat** [comment]
@razvanphp can you create a jsfiddle to test the piece of code? I have access to a fex android and ios devices so i'm able to test the snippet on different types of devices!

**Comment by domialex** [comment]
The latest version doesn't work on Android Chrome/Firefox.
My fix:  I just $(this.element).blur() manually and it works.

**Comment by maximelebreton** [comment]
+1 on HTC One with Android 5.0.2

**Comment by maximelebreton** [comment]
i dont think that `msMaxTouchPoints` or `ontouchstart` variables are the problem, because i made this workaround based on the same variables and it works.

i've just added a little trick to improve accessibility. (but of course this is not perfect)


```
var isDatepickerVisible = false;

$('.datepicker').datepicker({
    disableTouchKeyboard: false

  }).on('show', function(e) {
    /**
     * hack to disable touch keyboard with blur() method,
     * but only if the datepicker is not visible (to minimize accessibility problems)
     * so with a second click, the keyboard appears
     */
    if ((window.navigator.msMaxTouchPoints || 'ontouchstart' in document)) {
      if (!isDatepickerVisible) {
        $('input', $(this))[0].blur();
      }
    }
    isDatepickerVisible = true;

  }).on('hide', function(e) {
    isDatepickerVisible = false;
  });
```

**Comment by acrobat** [comment]
@maximelebreton care to create a PR with a fix?
