### ISSUE TITLE
make DPGlobal accessible to the outer world

### ISSUE THREAD

**Issue by pjlammertyn** [uxsolutions/bootstrap-datepicker#86]
so we can use the parseDate and formatDate methods

ex
var DPGlobal = $.fn.datepicker.DPGlobal = {

**Comment by etalley** [comment]
I just accessed it like this 

     $.prototype.datepicker.DPGlobal.formatDate(d, 'mm/dd/yyyy', 'en');

probably not kosher but it gets the job done.
