### ISSUE TITLE
Add getDate() and setDate() methods

### ISSUE THREAD

**Issue by tkrotoff** [uxsolutions/bootstrap-datepicker#91]
jQuery UI datepicker comes with a method named [getDate()](http://jqueryui.com/demos/datepicker/#method-getDate) that returns a JavaScript Date object. It also provides a method named [setDate()](http://jqueryui.com/demos/datepicker/#method-setDate) that takes a JavaScript Date object or a string.
This would avoid users to parse the string back to a Date object. The best place for this is definitely inside bootstrap-datepicker source code as jQuery UI developers demonstrated.

Another benefit is that it would also solve [issue #29](https://github.com/eternicode/bootstrap-datepicker/issues/29).
The [jQuery timepicker by Jon Thornton](https://github.com/jonthornton/jquery-timepicker) uses this method inside [datepair.js](https://github.com/jonthornton/jquery-timepicker/blob/master/lib/datepair.js). If bootstrap-datepicker implements this method it will be easy for me to adapt Thornton's code to use bootstrap-datepicker instead of jQuery UI datepicker.

We will then end up with a nice Google calendar like date and time picker that follows Bootstrap style.

![](https://a248.e.akamai.net/camo.github.com/9d17129a5fd1be3872fdf699c8dd0f446d3ba855/687474703a2f2f6a6f6e74686f726e746f6e2e6769746875622e636f6d2f6a71756572792d74696d657069636b65722f6c69622f73637265656e73686f742e706e67)

**Comment by ashishsOB** [comment]
.datepicker("getDate") is not working for me either

**Comment by ashishsOB** [comment]
.datepicker("getDate") is not working for me either
I always get null

**Comment by renepupil** [comment]
For anyone who comes across this issue: If you try to set a date that is NOT within the range of the start and end date `setDate` will not work, hence `getDate` will give `null`.
